import { useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './game.css';

export const GAME_KELAS5_IPAS_BAB7=[
 {kode:'culture-match',judul:'Culture Match',ikon:'🎭',topik:'Seperti Apakah Budaya Daerahku?',tujuan:'Mencocokkan contoh unsur budaya dengan kategorinya.',mekanik:'Matching budaya'},
 {kode:'tradition-trail',judul:'Tradition Trail',ikon:'🧵',topik:'Seperti Apakah Budaya Daerahku?',tujuan:'Menyusun cara sederhana menghargai dan melestarikan budaya daerah.',mekanik:'Misi urutan'},
 {kode:'economy-chain',judul:'Economy Chain',ikon:'🏪',topik:'Kondisi Perekonomian di Daerahku',tujuan:'Menyusun alur produksi, distribusi, dan konsumsi.',mekanik:'Rantai ekonomi'},
 {kode:'local-economy-builder',judul:'Local Economy Builder',ikon:'🧺',topik:'Kondisi Perekonomian di Daerahku',tujuan:'Memilih kegiatan ekonomi yang sesuai dengan potensi daerah pada skenario sederhana.',mekanik:'Simulasi keputusan'},
 {kode:'local-pride-quest',judul:'Local Pride Quest',ikon:'⭐',topik:'Wah, Ternyata Daerahku Luar Biasa!',tujuan:'Mengidentifikasi hal yang dapat menjadi kebanggaan daerah dan cara menjaganya.',mekanik:'Quest daerah'},
] as const;
type Kode=typeof GAME_KELAS5_IPAS_BAB7[number]['kode'];
function CultureMatch(){const data=[['Tari tradisional','Seni'],['Bahasa daerah','Bahasa'],['Rumah adat','Arsitektur'],['Upacara adat','Tradisi']] as const;const[i,setI]=useState(0);const x=data[Math.min(i,data.length-1)];return <section className="game5-arena"><h2>Culture Match</h2>{i<data.length?<><div className="game5-target">{x[0]}</div><div className="game5-choice game5-choice--text">{['Seni','Bahasa','Arsitektur','Tradisi'].map(o=><button key={o} onClick={()=>{if(o===x[1])setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Semua unsur budaya cocok.</p>}</section>}
function TraditionTrail(){const urutan=['👀 Kenali budaya','🤝 Hargai perbedaan','📚 Pelajari makna','🎉 Ikut melestarikan'];const acak=['🎉 Ikut melestarikan','👀 Kenali budaya','📚 Pelajari makna','🤝 Hargai perbedaan'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Tradition Trail</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===urutan.length?'🏆 Jalur pelestarian budaya selesai.':'Pilih langkah berikutnya.'}</p></section>}
function EconomyChain(){const urutan=['🌾 Produksi','🚚 Distribusi','🛒 Konsumsi'];const acak=['🛒 Konsumsi','🌾 Produksi','🚚 Distribusi'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Susun alur ekonomi</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===3?'🏆 Alur produksi–distribusi–konsumsi tersusun.':'Pilih tahap berikutnya.'}</p></section>}
function LocalEconomyBuilder(){const m=useMemo(()=>[{q:'Daerah pesisir memiliki banyak hasil ikan.',a:'Pengolahan dan pemasaran hasil perikanan',o:['Pengolahan dan pemasaran hasil perikanan','Perkebunan teh dataran tinggi','Peternakan rusa kutub']},{q:'Daerah memiliki kerajinan khas.',a:'Mengembangkan kerajinan dan promosi lokal',o:['Mengembangkan kerajinan dan promosi lokal','Menghilangkan semua produk lokal','Membuang bahan baku']}],[]);const[i,setI]=useState(0);const x=m[Math.min(i,m.length-1)];return <section className="game5-arena"><h2>Local Economy Builder</h2>{i<m.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Potensi daerah berhasil dipasangkan.</p>}</section>}
function LocalPrideQuest(){const m=useMemo(()=>[{q:'Budaya daerah mulai jarang dikenal siswa.',a:'Pelajari dan tampilkan secara menghargai',o:['Pelajari dan tampilkan secara menghargai','Abaikan seluruh budaya','Ejek perbedaan']},{q:'Lingkungan wisata daerah mulai kotor.',a:'Jaga kebersihan dan ajak pengunjung tertib',o:['Jaga kebersihan dan ajak pengunjung tertib','Tambah sampah','Rusak fasilitas']}],[]);const[i,setI]=useState(0);const x=m[Math.min(i,m.length-1)];return <section className="game5-arena"><h2>Local Pride Quest</h2>{i<m.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">⭐ Quest selesai. Kebanggaan daerah dapat dijaga melalui tindakan nyata.</p>}</section>}
export function GameKelas5Bab7Screen(){const{gameKode}=useParams();const p=GAME_KELAS5_IPAS_BAB7.find(x=>x.kode===gameKode);if(!p)return <main className="game5-runner"><Link to={RUTE.game}>← Kembali</Link><h1>Game tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'culture-match':<CultureMatch/>,'tradition-trail':<TraditionTrail/>,'economy-chain':<EconomyChain/>,'local-economy-builder':<LocalEconomyBuilder/>,'local-pride-quest':<LocalPrideQuest/>};return <main className="game5-runner"><header className="game5-header"><Link to={RUTE.game}>←</Link><div><small>IPAS Kelas V · Bab 7 · {p.topik}</small><h1>{p.ikon} {p.judul}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
