import { useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './game.css';

export const GAME_KELAS5_IPAS_BAB8=[
 {kode:'earth-change-detective',judul:'Earth Change Detective',ikon:'🔎',topik:'Bumi Berubah',tujuan:'Mengidentifikasi penyebab perubahan lingkungan dari contoh peristiwa.',mekanik:'Detektif sebab'},
 {kode:'pollution-sort',judul:'Pollution Sort',ikon:'🏭',topik:'Oh, Lingkungan Jadi Rusak',tujuan:'Mengelompokkan contoh pencemaran berdasarkan lingkungan yang terdampak.',mekanik:'Sortir pencemaran'},
 {kode:'waste-rescue',judul:'Waste Rescue',ikon:'♻️',topik:'Oh, Lingkungan Jadi Rusak',tujuan:'Memilih pengelolaan sampah yang lebih tepat pada skenario sederhana.',mekanik:'Misi sampah'},
 {kode:'eco-city-balance',judul:'Eco City Balance',ikon:'🏙️',topik:'Permasalahan Lingkungan Mengancam Kehidupan',tujuan:'Menyeimbangkan ruang hijau, pengelolaan sampah, dan transportasi pada model kota.',mekanik:'Simulasi keseimbangan'},
 {kode:'cause-effect-chain',judul:'Cause & Effect Chain',ikon:'🔗',topik:'Permasalahan Lingkungan Mengancam Kehidupan',tujuan:'Menyusun hubungan sebab-akibat masalah lingkungan.',mekanik:'Urutan sebab-akibat'},
] as const;
type Kode=typeof GAME_KELAS5_IPAS_BAB8[number]['kode'];
function ChangeDetective(){const kasus=useMemo(()=>[{q:'Hujan deras membawa tanah dari lereng.',a:'Erosi',o:['Erosi','Pemantulan','Magnet']},{q:'Sampah menumpuk menyumbat aliran air.',a:'Gangguan lingkungan oleh sampah',o:['Gangguan lingkungan oleh sampah','Pembiasan','Getaran']},{q:'Pohon berkurang dan tanah makin terbuka.',a:'Tutupan lahan berkurang',o:['Tutupan lahan berkurang','Arus listrik','Bunyi']}],[]);const[i,setI]=useState(0);const x=kasus[Math.min(i,kasus.length-1)];return <section className="game5-arena"><h2>Earth Change Detective</h2>{i<kasus.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🔎 Semua kasus terpecahkan.</p>}</section>}
function PollutionSort(){const data=[['Asap kendaraan','Udara'],['Limbah cair ke sungai','Air'],['Sampah plastik di tanah','Tanah'],['Asap pembakaran','Udara']] as const;const[i,setI]=useState(0);const x=data[Math.min(i,data.length-1)];return <section className="game5-arena"><h2>Pollution Sort</h2>{i<data.length?<><div className="game5-target">{x[0]}</div><div className="game5-choice"><button onClick={()=>{if(x[1]==='Udara')setI(i+1)}}>Udara</button><button onClick={()=>{if(x[1]==='Air')setI(i+1)}}>Air</button><button onClick={()=>{if(x[1]==='Tanah')setI(i+1)}}>Tanah</button></div></>:<p className="game5-feedback">🏆 Semua pencemaran terkelompok.</p>}</section>}
function WasteRescue(){const m=useMemo(()=>[{q:'Botol plastik bekas yang masih dapat dipakai ulang.',a:'Gunakan ulang atau masukkan ke alur daur ulang yang sesuai',o:['Gunakan ulang atau masukkan ke alur daur ulang yang sesuai','Buang ke sungai','Bakar sembarangan']},{q:'Sisa daun dari halaman.',a:'Kelola sebagai bahan organik/kompos bila memungkinkan',o:['Kelola sebagai bahan organik/kompos bila memungkinkan','Campur ke sungai','Buang sembarangan']}],[]);const[i,setI]=useState(0);const x=m[Math.min(i,m.length-1)];return <section className="game5-arena"><h2>Waste Rescue</h2>{i<m.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">♻️ Misi selesai.</p>}</section>}
function EcoCity(){const[hijau,setHijau]=useState(40);const[sampah,setSampah]=useState(60);const[transport,setTransport]=useState(40);const skor=Math.round((hijau+sampah+(100-transport))/3);return <section className="game5-arena"><h2>Eco City Balance</h2><label className="game5-slider">Ruang hijau <input type="range" min="0" max="100" value={hijau} onChange={e=>setHijau(Number(e.target.value))}/></label><label className="game5-slider">Pengelolaan sampah <input type="range" min="0" max="100" value={sampah} onChange={e=>setSampah(Number(e.target.value))}/></label><label className="game5-slider">Emisi transportasi model <input type="range" min="0" max="100" value={transport} onChange={e=>setTransport(Number(e.target.value))}/></label><p className="game5-feedback">Skor lingkungan kota model: <b>{skor}</b>. Coba capai ≥80.</p></section>}
function CauseEffect(){const urutan=['🗑️ Sampah tidak terkelola','🚧 Saluran tersumbat','🌧️ Air meluap','🏠 Lingkungan terdampak'];const acak=['🌧️ Air meluap','🗑️ Sampah tidak terkelola','🏠 Lingkungan terdampak','🚧 Saluran tersumbat'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Cause & Effect Chain</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===4?'🏆 Rantai sebab-akibat selesai.':'Pilih akibat berikutnya.'}</p></section>}
export function GameKelas5Bab8Screen(){const{gameKode}=useParams();const p=GAME_KELAS5_IPAS_BAB8.find(x=>x.kode===gameKode);if(!p)return <main className="game5-runner"><Link to={RUTE.game}>← Kembali</Link><h1>Game tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'earth-change-detective':<ChangeDetective/>,'pollution-sort':<PollutionSort/>,'waste-rescue':<WasteRescue/>,'eco-city-balance':<EcoCity/>,'cause-effect-chain':<CauseEffect/>};return <main className="game5-runner"><header className="game5-header"><Link to={RUTE.game}>←</Link><div><small>IPAS Kelas V · Bab 8 · {p.topik}</small><h1>{p.ikon} {p.judul}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
