import { useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './game.css';

export const GAME_KELAS5_IPAS_BAB6=[
 {kode:'archipelago-map',judul:'Archipelago Map Quest',ikon:'🗺️',topik:'Bagaimana Bentuk Indonesiaku?',tujuan:'Mengenali bahwa Indonesia terdiri atas banyak pulau dan wilayah perairan.',mekanik:'Peta sentuh'},
 {kode:'biodiversity-sort',judul:'Biodiversity Sort',ikon:'🦜',topik:'Indonesiaku Kaya Hayatinya',tujuan:'Mengelompokkan contoh keanekaragaman hayati berdasarkan kelompoknya.',mekanik:'Sortir kategori'},
 {kode:'habitat-match',judul:'Habitat Match',ikon:'🌳',topik:'Indonesiaku Kaya Hayatinya',tujuan:'Mencocokkan makhluk hidup dengan habitat yang sesuai.',mekanik:'Matching habitat'},
 {kode:'resource-hunt',judul:'Resource Hunt',ikon:'⛏️',topik:'Indonesiaku Kaya Alamnya',tujuan:'Membedakan contoh sumber daya alam berdasarkan asal dan pemanfaatannya.',mekanik:'Berburu sumber daya'},
 {kode:'sustainable-choice',judul:'Sustainable Choice',ikon:'♻️',topik:'Indonesiaku Kaya Alamnya',tujuan:'Memilih pemanfaatan sumber daya yang lebih bijak pada skenario sederhana.',mekanik:'Misi keputusan'},
] as const;
type Kode=typeof GAME_KELAS5_IPAS_BAB6[number]['kode'];
function ArchipelagoMap(){const pulau=['Sumatra','Jawa','Kalimantan','Sulawesi','Papua'];const[i,setI]=useState(0);return <section className="game5-arena"><h2>Temukan pulau berikutnya</h2><div className="game5-world">🗺️ Indonesia</div>{i<pulau.length?<><div className="game5-target">Target: {pulau[i]}</div><div className="game5-choice game5-choice--text">{[...pulau].sort().map(p=><button key={p} disabled={pulau.indexOf(p)<i} onClick={()=>{if(p===pulau[i])setI(i+1)}}>{p}</button>)}</div></>:<p className="game5-feedback">🏆 Lima pulau besar berhasil dikenali.</p>}</section>}
function BiodiversitySort(){const data=[['🌾 Padi','Tumbuhan'],['🦜 Burung','Hewan'],['🌴 Kelapa','Tumbuhan'],['🐟 Ikan','Hewan']] as const;const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=data[Math.min(i,data.length-1)];return <section className="game5-arena"><h2>Biodiversity Sort</h2>{i<data.length?<><div className="game5-target">{x[0]}</div><div className="game5-choice"><button onClick={()=>{if(x[1]==='Tumbuhan')setSkor(skor+100);setI(i+1)}}>Tumbuhan</button><button onClick={()=>{if(x[1]==='Hewan')setSkor(skor+100);setI(i+1)}}>Hewan</button></div></>:<p className="game5-feedback">🏆 Skor {skor}/{data.length*100}</p>}</section>}
function HabitatMatch(){const ronde=useMemo(()=>[{q:'🐠 Ikan karang',a:'Laut',o:['Laut','Pegunungan','Sawah']},{q:'🌾 Padi',a:'Sawah',o:['Hutan bakau','Sawah','Laut']},{q:'🦧 Orangutan',a:'Hutan',o:['Hutan','Pantai berpasir','Danau buatan']}],[]);const[i,setI]=useState(0);const x=ronde[Math.min(i,ronde.length-1)];return <section className="game5-arena"><h2>Habitat Match</h2>{i<ronde.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Semua habitat cocok.</p>}</section>}
function ResourceHunt(){const data=[['☀️ Matahari','Dapat diperbarui'],['🌳 Hutan','Dapat diperbarui jika dikelola'],['🛢️ Minyak bumi','Tidak dapat diperbarui cepat'],['💨 Angin','Dapat diperbarui']] as const;const[i,setI]=useState(0);const x=data[Math.min(i,data.length-1)];return <section className="game5-arena"><h2>Resource Hunt</h2>{i<data.length?<><div className="game5-target">{x[0]}</div><div className="game5-choice game5-choice--text">{['Dapat diperbarui','Dapat diperbarui jika dikelola','Tidak dapat diperbarui cepat'].map(o=><button key={o} onClick={()=>{if(o===x[1])setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Klasifikasi sumber daya selesai.</p>}</section>}
function SustainableChoice(){const misi=useMemo(()=>[{q:'Hutan dimanfaatkan untuk kayu. Pilihan yang lebih bijak?',a:'Tebang pilih dan tanam kembali',o:['Tebang pilih dan tanam kembali','Tebang semua pohon','Bakar lahan']},{q:'Sumber air mulai berkurang.',a:'Gunakan air seperlunya dan lindungi sumbernya',o:['Gunakan air seperlunya dan lindungi sumbernya','Biarkan keran terbuka','Buang sampah ke sungai']}],[]);const[i,setI]=useState(0);const x=misi[Math.min(i,misi.length-1)];return <section className="game5-arena"><h2>Sustainable Choice</h2>{i<misi.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Pilihan bijak selesai.</p>}</section>}
export function GameKelas5Bab6Screen(){const{gameKode}=useParams();const p=GAME_KELAS5_IPAS_BAB6.find(x=>x.kode===gameKode);if(!p)return <main className="game5-runner"><Link to={RUTE.game}>← Kembali</Link><h1>Game tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'archipelago-map':<ArchipelagoMap/>,'biodiversity-sort':<BiodiversitySort/>,'habitat-match':<HabitatMatch/>,'resource-hunt':<ResourceHunt/>,'sustainable-choice':<SustainableChoice/>};return <main className="game5-runner"><header className="game5-header"><Link to={RUTE.game}>←</Link><div><small>IPAS Kelas V · Bab 6 · {p.topik}</small><h1>{p.ikon} {p.judul}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
