import { useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './game.css';

export const GAME_KELAS5_IPAS_BAB5 = [
  { kode:'breath-meter', judul:'Breath Meter', ikon:'🫁', topik:'Bagaimana Bernapas Membantuku Melakukan Aktivitas Sehari-hari?', tujuan:'Menyesuaikan frekuensi napas dengan tingkat aktivitas pada simulasi.', mekanik:'Kontrol ritme' },
  { kode:'air-route', judul:'Air Route Mission', ikon:'🌬️', topik:'Bagaimana Bernapas Membantuku Melakukan Aktivitas Sehari-hari?', tujuan:'Menyusun jalur udara secara sederhana dari luar tubuh menuju paru-paru.', mekanik:'Urutan jalur' },
  { kode:'nutrient-match', judul:'Nutrient Match', ikon:'🥗', topik:'Mengapa Kita Perlu Makan dan Minum?', tujuan:'Mencocokkan contoh zat gizi dengan fungsi umumnya bagi tubuh.', mekanik:'Matching fungsi' },
  { kode:'digestion-journey', judul:'Digestion Journey', ikon:'🍽️', topik:'Mengapa Kita Perlu Makan dan Minum?', tujuan:'Menyusun perjalanan makanan melalui organ pencernaan utama secara sederhana.', mekanik:'Misi berantai' },
  { kode:'growth-timeline', judul:'Growth Timeline', ikon:'🌱', topik:'Bagaimana Aku Tumbuh Besar?', tujuan:'Menyusun tahapan pertumbuhan manusia dan mengenali bahwa kebutuhan berubah seiring usia.', mekanik:'Timeline' },
] as const;

type Kode=typeof GAME_KELAS5_IPAS_BAB5[number]['kode'];

function BreathMeter(){const[aktivitas,setAktivitas]=useState<'duduk'|'jalan'|'lari'>('duduk');const[napas,setNapas]=useState(12);const target=aktivitas==='duduk'?12:aktivitas==='jalan'?20:30;const selisih=Math.abs(napas-target);return <section className="game5-arena"><h2>Sesuaikan ritme napas</h2><div className="game5-components">{(['duduk','jalan','lari'] as const).map(a=><button key={a} className={aktivitas===a?'aktif':''} onClick={()=>setAktivitas(a)}>{a==='duduk'?'🪑 Duduk':a==='jalan'?'🚶 Jalan':'🏃 Lari'}</button>)}</div><label className="game5-slider">Frekuensi napas simulasi <input type="range" min="8" max="40" value={napas} onChange={e=>setNapas(Number(e.target.value))}/><b>{napas}</b></label><p className="game5-feedback">{selisih<=3?'✅ Ritme simulasi sesuai aktivitas.':'Atur ritme hingga mendekati kebutuhan aktivitas pada model.'}</p></section>}
function AirRoute(){const urutan=['👃 Hidung','🫁 Saluran napas','🫁 Paru-paru','🔴 Pertukaran gas'];const acak=['🫁 Paru-paru','👃 Hidung','🔴 Pertukaran gas','🫁 Saluran napas'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Air Route Mission</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===urutan.length?'🏆 Jalur udara selesai.':'Pilih tahap berikutnya.'}</p></section>}
function NutrientMatch(){const ronde=useMemo(()=>[{q:'Karbohidrat',a:'Sumber energi',o:['Sumber energi','Membantu pembentukan jaringan','Mengatur berbagai proses tubuh']},{q:'Protein',a:'Membantu pembentukan jaringan',o:['Membantu pembentukan jaringan','Sumber cahaya','Membuat magnet']},{q:'Vitamin dan mineral',a:'Mengatur berbagai proses tubuh',o:['Mengatur berbagai proses tubuh','Membuat bunyi','Mengubah tanah']}],[]);const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=ronde[Math.min(i,ronde.length-1)];return <section className="game5-arena"><h2>Nutrient Match</h2>{i<ronde.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setSkor(skor+100);setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Selesai! Skor {skor}/{ronde.length*100}</p>}</section>}
function DigestionJourney(){const urutan=['👄 Mulut','🧪 Lambung','🌀 Usus halus','🚰 Usus besar'];const opsi=['🚰 Usus besar','👄 Mulut','🌀 Usus halus','🧪 Lambung'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Digestion Journey</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{opsi.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===urutan.length?'🏆 Perjalanan makanan selesai.':'Pilih organ berikutnya.'}</p></section>}
function GrowthTimeline(){const urutan=['👶 Bayi','🧒 Anak-anak','🧑 Remaja','🧑‍🦱 Dewasa','👵 Lansia'];const acak=['🧑‍🦱 Dewasa','👶 Bayi','👵 Lansia','🧒 Anak-anak','🧑 Remaja'];const[n,setN]=useState(0);return <section className="game5-arena"><h2>Growth Timeline</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===urutan.length?'🏆 Tahapan pertumbuhan tersusun. Setiap tahap memiliki kebutuhan dan kemampuan yang berkembang.':'Susun tahap berikutnya.'}</p></section>}

export function GameKelas5Bab5Screen(){const{gameKode}=useParams();const p=GAME_KELAS5_IPAS_BAB5.find(x=>x.kode===gameKode);if(!p)return <main className="game5-runner"><Link to={RUTE.game}>← Kembali</Link><h1>Game tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'breath-meter':<BreathMeter/>,'air-route':<AirRoute/>,'nutrient-match':<NutrientMatch/>,'digestion-journey':<DigestionJourney/>,'growth-timeline':<GrowthTimeline/>};return <main className="game5-runner"><header className="game5-header"><Link to={RUTE.game}>←</Link><div><small>IPAS Kelas V · Bab 5 · {p.topik}</small><h1>{p.ikon} {p.judul}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
