import { useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './game.css';

export const GAME_KELAS5_IPAS_BAB4 = [
  { kode:'earth-zone-puzzle', judul:'Earth Zone Puzzle', ikon:'🌍', topik:'Ada Apa Saja di Bumi Kita?', tujuan:'Mencocokkan bagian permukaan Bumi dengan contoh kenampakannya.', mekanik:'Puzzle kategori' },
  { kode:'landform-match', judul:'Landform Match', ikon:'⛰️', topik:'Ada Apa Saja di Bumi Kita?', tujuan:'Mencocokkan kenampakan alam dengan cirinya.', mekanik:'Matching visual' },
  { kode:'weathering-detective', judul:'Weathering Detective', ikon:'🪨', topik:'Mengapa Bentuk Permukaan Bumi Berubah-ubah?', tujuan:'Mengenali penyebab perubahan permukaan Bumi dari contoh peristiwa.', mekanik:'Detektif sebab' },
  { kode:'volcano-alert', judul:'Volcano Alert', ikon:'🌋', topik:'Bagaimana Bumi Kita Berubah?', tujuan:'Memilih tindakan pengamatan yang tepat saat simulasi aktivitas gunung meningkat.', mekanik:'Misi indikator' },
  { kode:'earth-change-timeline', judul:'Earth Change Timeline', ikon:'🕒', topik:'Bagaimana Bumi Kita Berubah?', tujuan:'Menyusun urutan perubahan bentang alam dari proses yang diamati.', mekanik:'Urutan peristiwa' },
] as const;

type Kode=typeof GAME_KELAS5_IPAS_BAB4[number]['kode'];

function EarthZonePuzzle(){const item=[['🌊 Laut','Perairan'],['🏔️ Pegunungan','Daratan'],['🏞️ Sungai','Perairan'],['🏜️ Gurun','Daratan'],['🏝️ Pulau','Daratan']] as const;const [i,setI]=useState(0);const [skor,setSkor]=useState(0);const x=item[Math.min(i,item.length-1)];return <section className="game5-arena"><h2>Daratan atau perairan?</h2>{i<item.length?<><div className="game5-target">{x[0]}</div><div className="game5-choice"><button onClick={()=>{if(x[1]==='Daratan')setSkor(skor+100);setI(i+1)}}>Daratan</button><button onClick={()=>{if(x[1]==='Perairan')setSkor(skor+100);setI(i+1)}}>Perairan</button></div></>:<p className="game5-feedback">🏆 Selesai! Skor {skor}/{item.length*100}</p>}</section>}

function LandformMatch(){const ronde=[{q:'Daerah tinggi memanjang dengan lereng dan puncak',a:'Pegunungan',o:['Pegunungan','Pantai','Sungai']},{q:'Aliran air yang bergerak dari tempat tinggi ke rendah',a:'Sungai',o:['Danau','Sungai','Bukit']},{q:'Batas antara daratan dan laut',a:'Pantai',o:['Lembah','Pantai','Gunung']}];const [i,setI]=useState(0);const [skor,setSkor]=useState(0);const x=ronde[Math.min(i,ronde.length-1)];return <section className="game5-arena"><h2>Landform Match</h2>{i<ronde.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setSkor(skor+100);setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🏆 Semua kenampakan cocok. Skor {skor}/{ronde.length*100}</p>}</section>}

function WeatheringDetective(){const kasus=useMemo(()=>[{q:'Batu retak setelah berulang kali terkena panas dan dingin.',a:'Perubahan suhu',o:['Perubahan suhu','Magnet','Cahaya']},{q:'Tanah di lereng terbawa aliran air hujan.',a:'Erosi air',o:['Erosi air','Pembiasan','Getaran bunyi']},{q:'Akar tumbuhan masuk ke celah batu dan memperlebar retakan.',a:'Aktivitas makhluk hidup',o:['Aktivitas makhluk hidup','Arus listrik','Bayangan']}],[]);const [i,setI]=useState(0);const [skor,setSkor]=useState(0);const x=kasus[Math.min(i,kasus.length-1)];return <section className="game5-arena"><h2>Weathering Detective</h2>{i<kasus.length?<><div className="game5-target">{x.q}</div><div className="game5-choice game5-choice--text">{x.o.map(o=><button key={o} onClick={()=>{if(o===x.a)setSkor(skor+100);setI(i+1)}}>{o}</button>)}</div></>:<p className="game5-feedback">🔎 Kasus selesai. Skor {skor}/{kasus.length*100}</p>}</section>}

function VolcanoAlert(){const [level,setLevel]=useState(1);const indikator=['Tenang','Asap meningkat','Getaran meningkat','Aktivitas sangat tinggi'];return <section className="game5-arena"><h2>Volcano Alert</h2><div className="game5-world">🌋 {indikator[level-1]}</div><div className="game5-choice game5-choice--text"><button onClick={()=>setLevel(Math.min(4,level+1))}>📈 Naikkan aktivitas</button><button onClick={()=>setLevel(Math.max(1,level-1))}>📉 Turunkan aktivitas</button></div><p className="game5-feedback">Level {level}: {level<3?'Amati perubahan indikator simulasi.':'Indikator meningkat. Dalam kehidupan nyata, ikuti informasi resmi dan arahan orang dewasa/petugas.'}</p></section>}

function EarthChangeTimeline(){const urutan=['🌧️ Hujan turun','💧 Air mengalir di lereng','🟤 Tanah terbawa','🏞️ Endapan terkumpul'];const acak=['🏞️ Endapan terkumpul','🌧️ Hujan turun','🟤 Tanah terbawa','💧 Air mengalir di lereng'];const [n,setN]=useState(0);return <section className="game5-arena"><h2>Susun perubahan permukaan</h2><div className="game5-chain">{urutan.map((x,i)=><span key={x} className={i<n?'aktif':''}>{i<n?x:'❔'}</span>)}</div><div className="game5-choice game5-choice--text">{acak.map(x=><button key={x} disabled={urutan.indexOf(x)<n} onClick={()=>{if(x===urutan[n])setN(n+1)}}>{x}</button>)}</div><p className="game5-feedback">{n===urutan.length?'🏆 Urutan proses perubahan permukaan selesai.':'Pilih peristiwa berikutnya.'}</p></section>}

export function GameKelas5Bab4Screen(){const{gameKode}=useParams();const p=GAME_KELAS5_IPAS_BAB4.find(x=>x.kode===gameKode);if(!p)return <main className="game5-runner"><Link to={RUTE.game}>← Kembali</Link><h1>Game tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'earth-zone-puzzle':<EarthZonePuzzle/>,'landform-match':<LandformMatch/>,'weathering-detective':<WeatheringDetective/>,'volcano-alert':<VolcanoAlert/>,'earth-change-timeline':<EarthChangeTimeline/>};return <main className="game5-runner"><header className="game5-header"><Link to={RUTE.game}>←</Link><div><small>IPAS Kelas V · Bab 4 · {p.topik}</small><h1>{p.ikon} {p.judul}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
