import { useEffect, useRef, useState } from 'react';
import { auditIntegritasKurikulum, type LaporanIntegritasKurikulum } from '../../lib/storage/kurikulumAdminRepo';
import './kurikulum-admin.css';

export function MuatCpScreen() {
  const [audit,setAudit]=useState<LaporanIntegritasKurikulum|null>(null);const [berkas,setBerkas]=useState<File|null>(null);const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{void auditIntegritasKurikulum().then(setAudit);},[]);
  return <main className="halaman-kurikulum halaman-muat-cp" data-testid="muat-cp"><header className="kop-kurikulum"><div><p className="label-data">Hanya operator sekolah</p><h1>Muat Capaian Pembelajaran Resmi</h1><p>Teks tidak pernah diperbaiki, diringkas, atau dilengkapi otomatis.</p></div></header><section className="alur-impor"><article className="aktif"><b>1</b><span>Unggah dokumen</span></article><article><b>2</b><span>Petakan kolom</span></article><article><b>3</b><span>Periksa & verifikasi</span></article><article><b>4</b><span>Kunci sebagai resmi</span></article></section><div className="tata-muat-cp"><section className="drop-cp" onClick={()=>inputRef.current?.click()}><span>↑</span><h2>{berkas?berkas.name:'Letakkan berkas di sini'}</h2><p>PDF, DOCX, XLSX, CSV, atau JSON · maksimum 20 MB</p><button type="button">Pilih Berkas</button><input ref={inputRef} className="sr-only" type="file" accept=".pdf,.docx,.xlsx,.csv,.json" onChange={(e)=>setBerkas(e.target.files?.[0]??null)}/></section><section className="cakupan-cp"><h2>Cakupan seed final</h2><article><span>CP non-agama 046/H/KR/2025</span><strong>29 / 29</strong></article><article><span>CP agama 020/2026</span><strong>18 / 18</strong></article><article><span>Elemen bertaut</span><strong>221</strong></article><article><span>TP Rekomendasi</span><strong>212</strong></article><p className={audit?.masalah.length?'peringatan':'berhasil'}>{audit?.masalah.length?`${audit.masalah.length} masalah integritas perlu diperiksa.`:'Seed final lengkap; pemuatan baru akan membuat versi, bukan menimpa baris lama.'}</p></section></div>{berkas?<section className="keadaan-kosong keadaan-kosong--dalam"><h2>Berkas siap untuk tahap pemetaan</h2><p>Parser impor operator mengikuti kontrak Tahap 10 dan tidak dijalankan otomatis dari pemilihan berkas. Data final aktif tetap tidak berubah.</p><button className="tombol-guru" type="button" onClick={()=>setBerkas(null)}>Batalkan Berkas</button></section>:null}</main>;
}
