import { useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './vlab.css';

export const VLAB_KELAS5_IPAS_BAB7=[
 {kode:'culture-diversity',nama:'Culture Diversity Simulator',ikon:'🎭',topik:'Seperti Apakah Budaya Daerahku?',tujuan:'Mengamati bagaimana banyak unsur budaya dapat hadir bersama dalam satu daerah.'},
 {kode:'culture-preservation',nama:'Culture Preservation Lab',ikon:'🧵',topik:'Seperti Apakah Budaya Daerahku?',tujuan:'Membandingkan dampak tingkat partisipasi masyarakat terhadap keberlanjutan budaya pada model.'},
 {kode:'economic-flow',nama:'Economic Flow Simulator',ikon:'🏪',topik:'Kondisi Perekonomian di Daerahku',tujuan:'Mengamati alur produksi, distribusi, dan konsumsi.'},
 {kode:'local-economy-mix',nama:'Local Economy Mix',ikon:'🧺',topik:'Kondisi Perekonomian di Daerahku',tujuan:'Membandingkan komposisi beberapa sektor ekonomi lokal pada model.'},
 {kode:'tourism-impact',nama:'Local Potential Simulator',ikon:'⭐',topik:'Wah, Ternyata Daerahku Luar Biasa!',tujuan:'Mengamati hubungan promosi potensi daerah, kunjungan, dan kebersihan lingkungan pada model.'},
] as const;
type Kode=typeof VLAB_KELAS5_IPAS_BAB7[number]['kode'];
function CultureDiversity(){const[bahasa,setBahasa]=useState(3);const[seni,setSeni]=useState(4);const[tradisi,setTradisi]=useState(3);return <div className="vlab5-stage"><div className="vlab5-scene">🗣️ {bahasa} · 🎭 {seni} · 🧵 {tradisi}</div><label>Ragam bahasa <input type="range" min="1" max="8" value={bahasa} onChange={e=>setBahasa(Number(e.target.value))}/></label><label>Ragam seni <input type="range" min="1" max="8" value={seni} onChange={e=>setSeni(Number(e.target.value))}/></label><label>Ragam tradisi <input type="range" min="1" max="8" value={tradisi} onChange={e=>setTradisi(Number(e.target.value))}/></label><p className="vlab5-observe">Jumlah unsur budaya pada model: <b>{bahasa+seni+tradisi}</b>. Keragaman dapat hidup berdampingan jika saling dihargai.</p></div>}
function CulturePreservation(){const[partisipasi,setPartisipasi]=useState(60);const[dokumentasi,setDokumentasi]=useState(50);const indeks=Math.round((partisipasi+dokumentasi)/2);return <div className="vlab5-stage"><div className="vlab5-scene">🎭 📚 🤝</div><label>Partisipasi warga <input type="range" min="0" max="100" value={partisipasi} onChange={e=>setPartisipasi(Number(e.target.value))}/></label><label>Dokumentasi/pembelajaran <input type="range" min="0" max="100" value={dokumentasi} onChange={e=>setDokumentasi(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks pelestarian model: <b>{indeks}</b>. Keterlibatan dan pembelajaran membantu budaya tetap dikenal.</p></div>}
function EconomicFlow(){const[produksi,setProduksi]=useState(70);const[distribusi,setDistribusi]=useState(60);const[konsumsi,setKonsumsi]=useState(50);const aliran=Math.min(produksi,distribusi,konsumsi);return <div className="vlab5-stage"><div className="vlab5-scene">🌾 → 🚚 → 🛒</div><label>Produksi <input type="range" min="0" max="100" value={produksi} onChange={e=>setProduksi(Number(e.target.value))}/></label><label>Distribusi <input type="range" min="0" max="100" value={distribusi} onChange={e=>setDistribusi(Number(e.target.value))}/></label><label>Konsumsi <input type="range" min="0" max="100" value={konsumsi} onChange={e=>setKonsumsi(Number(e.target.value))}/></label><p className="vlab5-observe">Kapasitas aliran ekonomi model: <b>{aliran}</b>. Tahap yang paling rendah dapat menjadi hambatan pada alur.</p></div>}
function EconomyMix(){const[tani,setTani]=useState(40);const[jasa,setJasa]=useState(30);const[kerajinan,setKerajinan]=useState(30);return <div className="vlab5-stage"><div className="vlab5-scene">🌾 {tani}% · 🏪 {jasa}% · 🧺 {kerajinan}%</div><label>Pertanian <input type="range" min="0" max="100" value={tani} onChange={e=>setTani(Number(e.target.value))}/></label><label>Jasa <input type="range" min="0" max="100" value={jasa} onChange={e=>setJasa(Number(e.target.value))}/></label><label>Kerajinan <input type="range" min="0" max="100" value={kerajinan} onChange={e=>setKerajinan(Number(e.target.value))}/></label><p className="vlab5-observe">Model menunjukkan bahwa daerah dapat memiliki campuran kegiatan ekonomi yang berbeda sesuai potensi dan kebutuhan.</p></div>}
function TourismImpact(){const[promosi,setPromosi]=useState(50);const[kebersihan,setKebersihan]=useState(70);const[kunjungan,setKunjungan]=useState(40);const nilai=Math.round((promosi+kebersihan+kunjungan)/3);return <div className="vlab5-stage"><div className="vlab5-scene">⭐ 📣 🧹</div><label>Promosi potensi daerah <input type="range" min="0" max="100" value={promosi} onChange={e=>setPromosi(Number(e.target.value))}/></label><label>Kebersihan/fasilitas <input type="range" min="0" max="100" value={kebersihan} onChange={e=>setKebersihan(Number(e.target.value))}/></label><label>Kunjungan <input type="range" min="0" max="100" value={kunjungan} onChange={e=>setKunjungan(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks potensi terkelola pada model: <b>{nilai}</b>. Promosi perlu diimbangi perawatan lingkungan dan fasilitas.</p></div>}
export function VlabKelas5Bab7Screen(){const{labKode}=useParams();const p=VLAB_KELAS5_IPAS_BAB7.find(x=>x.kode===labKode);if(!p)return <main className="halaman-vlab"><Link to={RUTE.vlab}>← Kembali</Link><h1>VLAB tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'culture-diversity':<CultureDiversity/>,'culture-preservation':<CulturePreservation/>,'economic-flow':<EconomicFlow/>,'local-economy-mix':<EconomyMix/>,'tourism-impact':<TourismImpact/>};return <main className="vlab5-runner"><header><Link to={RUTE.vlab}>←</Link><div><small>IPAS Kelas V · Bab 7 · {p.topik}</small><h1>{p.ikon} {p.nama}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
