import { useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './vlab.css';

export const VLAB_KELAS5_IPAS_BAB4 = [
  { kode:'landform-builder', nama:'Landform Builder', ikon:'⛰️', topik:'Ada Apa Saja di Bumi Kita?', tujuan:'Membandingkan bentuk permukaan Bumi berdasarkan ketinggian dan cekungan.' },
  { kode:'slope-erosion', nama:'Slope Erosion Lab', ikon:'🌧️', topik:'Mengapa Bentuk Permukaan Bumi Berubah-ubah?', tujuan:'Mengamati pengaruh kemiringan dan hujan terhadap erosi pada model.' },
  { kode:'river-sediment', nama:'River Sediment Lab', ikon:'🏞️', topik:'Mengapa Bentuk Permukaan Bumi Berubah-ubah?', tujuan:'Mengamati pengangkutan dan pengendapan sedimen pada aliran air.' },
  { kode:'volcano-pressure', nama:'Volcano Pressure Model', ikon:'🌋', topik:'Bagaimana Bumi Kita Berubah?', tujuan:'Mengamati perubahan indikator tekanan pada model gunung api sederhana.' },
  { kode:'quake-wave', nama:'Earthquake Wave Model', ikon:'〰️', topik:'Bagaimana Bumi Kita Berubah?', tujuan:'Mengamati perambatan getaran pada model permukaan Bumi.' },
] as const;

type Kode=typeof VLAB_KELAS5_IPAS_BAB4[number]['kode'];

function LandformBuilder(){const[tinggi,setTinggi]=useState(50);const[cekung,setCekung]=useState(20);const bentuk=tinggi>70?'Pegunungan':cekung>60?'Cekungan/lembah':'Dataran/bukit rendah';return <div className="vlab5-stage"><div className="vlab5-scene">🌍 ⛰️ {bentuk}</div><label>Ketinggian relatif <input type="range" min="0" max="100" value={tinggi} onChange={e=>setTinggi(Number(e.target.value))}/><b>{tinggi}</b></label><label>Kedalaman cekungan <input type="range" min="0" max="100" value={cekung} onChange={e=>setCekung(Number(e.target.value))}/><b>{cekung}</b></label><p className="vlab5-observe">Model menunjukkan: <b>{bentuk}</b>. Ubah kedua kontrol untuk membandingkan bentuk permukaan.</p></div>}
function SlopeErosion(){const[hujan,setHujan]=useState(40);const[miring,setMiring]=useState(30);const[vegetasi,setVegetasi]=useState(40);const erosi=Math.max(0,Math.round((hujan*miring*(100-vegetasi))/10000));return <div className="vlab5-stage"><div className="vlab5-scene">🌧️ → ⛰️ → 🟤</div><label>Hujan <input type="range" min="0" max="100" value={hujan} onChange={e=>setHujan(Number(e.target.value))}/><b>{hujan}</b></label><label>Kemiringan <input type="range" min="0" max="100" value={miring} onChange={e=>setMiring(Number(e.target.value))}/><b>{miring}</b></label><label>Tutupan vegetasi <input type="range" min="0" max="100" value={vegetasi} onChange={e=>setVegetasi(Number(e.target.value))}/><b>{vegetasi}%</b></label><p className="vlab5-observe">Indeks erosi model: <b>{erosi}</b>. Bandingkan saat hujan/kemiringan naik dan vegetasi bertambah.</p></div>}
function RiverSediment(){const[arus,setArus]=useState(50);const[butir,setButir]=useState(50);const status=arus>butir+20?'Terangkut kuat':arus+20<butir?'Cepat mengendap':'Sebagian terangkut';return <div className="vlab5-stage"><div className="vlab5-scene">🏞️ 〰️ 🟤 〰️</div><label>Kecepatan arus <input type="range" min="0" max="100" value={arus} onChange={e=>setArus(Number(e.target.value))}/><b>{arus}</b></label><label>Ukuran sedimen <input type="range" min="0" max="100" value={butir} onChange={e=>setButir(Number(e.target.value))}/><b>{butir}</b></label><p className="vlab5-observe">Hasil model: <b>{status}</b>. Arus lebih kuat cenderung mampu membawa lebih banyak partikel sebelum mengendap.</p></div>}
function VolcanoPressure(){const[tekanan,setTekanan]=useState(20);const status=tekanan<40?'Rendah':tekanan<70?'Meningkat':'Tinggi';return <div className="vlab5-stage"><div className="vlab5-scene">🌋 {status==='Tinggi'?'💨💨':'💨'}</div><label>Indikator tekanan model <input type="range" min="0" max="100" value={tekanan} onChange={e=>setTekanan(Number(e.target.value))}/><b>{tekanan}</b></label><p className="vlab5-observe">Status model: <b>{status}</b>. Simulasi ini hanya untuk memahami hubungan perubahan indikator, bukan untuk memprediksi gunung api nyata.</p></div>}
function QuakeWave(){const[kekuatan,setKekuatan]=useState(30);const[jarak,setJarak]=useState(20);const terasa=Math.max(0,Math.round(kekuatan*(1-jarak/120)));return <div className="vlab5-stage"><div className="vlab5-scene">📍 〰️〰️〰️ 🏠</div><label>Kekuatan getaran model <input type="range" min="0" max="100" value={kekuatan} onChange={e=>setKekuatan(Number(e.target.value))}/><b>{kekuatan}</b></label><label>Jarak pengamatan <input type="range" min="0" max="100" value={jarak} onChange={e=>setJarak(Number(e.target.value))}/><b>{jarak}</b></label><p className="vlab5-observe">Amplitudo relatif di titik pengamatan: <b>{terasa}</b>. Ubah jarak dan kekuatan untuk melihat perubahan pada model.</p></div>}

export function VlabKelas5Bab4Screen(){const{labKode}=useParams();const p=VLAB_KELAS5_IPAS_BAB4.find(x=>x.kode===labKode);if(!p)return <main className="halaman-vlab"><Link to={RUTE.vlab}>← Kembali</Link><h1>VLAB tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'landform-builder':<LandformBuilder/>,'slope-erosion':<SlopeErosion/>,'river-sediment':<RiverSediment/>,'volcano-pressure':<VolcanoPressure/>,'quake-wave':<QuakeWave/>};return <main className="vlab5-runner"><header><Link to={RUTE.vlab}>←</Link><div><small>IPAS Kelas V · Bab 4 · {p.topik}</small><h1>{p.ikon} {p.nama}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
