import { useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './vlab.css';

export const VLAB_KELAS5_IPAS_BAB8=[
 {kode:'water-quality',nama:'Water Quality Lab',ikon:'💧',topik:'Oh, Lingkungan Jadi Rusak',tujuan:'Mengamati perubahan indeks kualitas air ketika jumlah limbah dan pengelolaan diubah.'},
 {kode:'air-quality',nama:'Air Quality Lab',ikon:'🌫️',topik:'Oh, Lingkungan Jadi Rusak',tujuan:'Mengamati perubahan kualitas udara pada model ketika emisi dan ruang hijau diubah.'},
 {kode:'waste-flow',nama:'Waste Flow Lab',ikon:'♻️',topik:'Permasalahan Lingkungan Mengancam Kehidupan',tujuan:'Mengamati aliran sampah dari sumber hingga pengelolaan pada model.'},
 {kode:'land-cover',nama:'Land Cover Lab',ikon:'🌳',topik:'Bumi Berubah',tujuan:'Mengamati hubungan tutupan lahan, limpasan air, dan erosi pada model.'},
 {kode:'environment-risk',nama:'Environment Risk Simulator',ikon:'⚠️',topik:'Permasalahan Lingkungan Mengancam Kehidupan',tujuan:'Menggabungkan beberapa faktor lingkungan untuk melihat perubahan tingkat risiko pada model.'},
] as const;
type Kode=typeof VLAB_KELAS5_IPAS_BAB8[number]['kode'];
function WaterQuality(){const[limbah,setLimbah]=useState(30);const[kelola,setKelola]=useState(60);const mutu=Math.max(0,100-limbah+Math.round(kelola/2));return <div className="vlab5-stage"><div className="vlab5-scene">🏭 → 💧 → 🐟</div><label>Limbah model <input type="range" min="0" max="100" value={limbah} onChange={e=>setLimbah(Number(e.target.value))}/></label><label>Pengelolaan <input type="range" min="0" max="100" value={kelola} onChange={e=>setKelola(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks kualitas air model: <b>{Math.min(100,mutu)}</b>. Limbah menurunkan kualitas, sedangkan pengelolaan yang baik membantu mengurangi dampak.</p></div>}
function AirQuality(){const[emisi,setEmisi]=useState(50);const[hijau,setHijau]=useState(50);const mutu=Math.max(0,Math.min(100,100-emisi+Math.round(hijau/2)));return <div className="vlab5-stage"><div className="vlab5-scene">🚗 💨 🌳</div><label>Emisi model <input type="range" min="0" max="100" value={emisi} onChange={e=>setEmisi(Number(e.target.value))}/></label><label>Ruang hijau <input type="range" min="0" max="100" value={hijau} onChange={e=>setHijau(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks kualitas udara model: <b>{mutu}</b>. Coba kurangi emisi dan tambah ruang hijau.</p></div>}
function WasteFlow(){const[sampah,setSampah]=useState(80);const[pilah,setPilah]=useState(40);const[olah,setOlah]=useState(40);const sisa=Math.max(0,Math.round(sampah*(1-pilah/200)*(1-olah/200)));return <div className="vlab5-stage"><div className="vlab5-scene">🏠 → 🗑️ → ♻️</div><label>Sampah masuk <input type="range" min="0" max="100" value={sampah} onChange={e=>setSampah(Number(e.target.value))}/></label><label>Pemilahan <input type="range" min="0" max="100" value={pilah} onChange={e=>setPilah(Number(e.target.value))}/></label><label>Pengolahan <input type="range" min="0" max="100" value={olah} onChange={e=>setOlah(Number(e.target.value))}/></label><p className="vlab5-observe">Sisa yang belum tertangani pada model: <b>{sisa}</b>. Pemilahan dan pengolahan menurunkan beban sisa.</p></div>}
function LandCover(){const[hijau,setHijau]=useState(60);const[hujan,setHujan]=useState(60);const limpasan=Math.max(0,Math.round(hujan*(100-hijau)/100));return <div className="vlab5-stage"><div className="vlab5-scene">🌧️ → 🌳/🟫 → 💧</div><label>Tutupan hijau <input type="range" min="0" max="100" value={hijau} onChange={e=>setHijau(Number(e.target.value))}/></label><label>Hujan <input type="range" min="0" max="100" value={hujan} onChange={e=>setHujan(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks limpasan model: <b>{limpasan}</b>. Tutupan lahan yang lebih baik membantu menahan air dan tanah pada model.</p></div>}
function EnvironmentRisk(){const[air,setAir]=useState(30);const[udara,setUdara]=useState(30);const[sampah,setSampah]=useState(30);const risiko=Math.round((air+udara+sampah)/3);return <div className="vlab5-stage"><div className="vlab5-scene">💧 🌫️ 🗑️ → ⚠️</div><label>Tekanan pada air <input type="range" min="0" max="100" value={air} onChange={e=>setAir(Number(e.target.value))}/></label><label>Tekanan pada udara <input type="range" min="0" max="100" value={udara} onChange={e=>setUdara(Number(e.target.value))}/></label><label>Masalah sampah <input type="range" min="0" max="100" value={sampah} onChange={e=>setSampah(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks risiko lingkungan model: <b>{risiko}</b>. Semakin banyak tekanan lingkungan, semakin tinggi risiko pada model.</p></div>}
export function VlabKelas5Bab8Screen(){const{labKode}=useParams();const p=VLAB_KELAS5_IPAS_BAB8.find(x=>x.kode===labKode);if(!p)return <main className="halaman-vlab"><Link to={RUTE.vlab}>← Kembali</Link><h1>VLAB tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'water-quality':<WaterQuality/>,'air-quality':<AirQuality/>,'waste-flow':<WasteFlow/>,'land-cover':<LandCover/>,'environment-risk':<EnvironmentRisk/>};return <main className="vlab5-runner"><header><Link to={RUTE.vlab}>←</Link><div><small>IPAS Kelas V · Bab 8 · {p.topik}</small><h1>{p.ikon} {p.nama}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
