import { useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './vlab.css';

export const VLAB_KELAS5_IPAS_BAB5 = [
  { kode:'breathing-rate', nama:'Breathing Rate Lab', ikon:'🫁', topik:'Bagaimana Bernapas Membantuku Melakukan Aktivitas Sehari-hari?', tujuan:'Mengamati perubahan frekuensi napas pada tingkat aktivitas berbeda.' },
  { kode:'lung-volume', nama:'Lung Volume Model', ikon:'🎈', topik:'Bagaimana Bernapas Membantuku Melakukan Aktivitas Sehari-hari?', tujuan:'Mengamati perubahan volume model paru-paru saat menarik dan mengembuskan napas.' },
  { kode:'nutrient-balance', nama:'Nutrient Balance Lab', ikon:'🥗', topik:'Mengapa Kita Perlu Makan dan Minum?', tujuan:'Membandingkan komposisi zat gizi dari beberapa kombinasi bahan makanan pada model.' },
  { kode:'digestion-time', nama:'Digestion Transit Lab', ikon:'🧪', topik:'Mengapa Kita Perlu Makan dan Minum?', tujuan:'Mengamati perjalanan makanan melalui tahapan pencernaan pada simulasi.' },
  { kode:'growth-support', nama:'Growth Support Lab', ikon:'🌱', topik:'Bagaimana Aku Tumbuh Besar?', tujuan:'Mengamati bagaimana kebiasaan sehat mendukung kesiapan belajar dan pertumbuhan pada model.' },
] as const;

type Kode=typeof VLAB_KELAS5_IPAS_BAB5[number]['kode'];

function BreathingRate(){const[aktivitas,setAktivitas]=useState(1);const rate=[12,18,28][aktivitas];return <div className="vlab5-stage"><div className="vlab5-scene">{aktivitas===0?'🪑':aktivitas===1?'🚶':'🏃'} 〰️ 🫁</div><div className="vlab5-components">{['Duduk','Berjalan','Berlari'].map((x,i)=><button key={x} className={i===aktivitas?'aktif':''} onClick={()=>setAktivitas(i)}>{x}</button>)}</div><p className="vlab5-observe">Frekuensi napas model: <b>{rate} kali/menit</b>. Aktivitas lebih berat meningkatkan kebutuhan pertukaran gas pada model.</p></div>}
function LungVolume(){const[tarik,setTarik]=useState(50);return <div className="vlab5-stage"><div className="vlab5-scene">🫁 {'◯'.repeat(Math.max(1,Math.round(tarik/20)))}</div><label>Tarik / hembuskan napas <input type="range" min="10" max="100" value={tarik} onChange={e=>setTarik(Number(e.target.value))}/><b>{tarik}%</b></label><p className="vlab5-observe">Volume model paru-paru berubah mengikuti gerakan simulasi. Bandingkan saat nilai dinaikkan dan diturunkan.</p></div>}
function NutrientBalance(){const[karbo,setKarbo]=useState(40);const[protein,setProtein]=useState(30);const[vitamin,setVitamin]=useState(30);const total=karbo+protein+vitamin;return <div className="vlab5-stage"><div className="vlab5-scene">🍚 {karbo}% · 🥚 {protein}% · 🥦 {vitamin}%</div><label>Karbohidrat <input type="range" min="0" max="100" value={karbo} onChange={e=>setKarbo(Number(e.target.value))}/></label><label>Protein <input type="range" min="0" max="100" value={protein} onChange={e=>setProtein(Number(e.target.value))}/></label><label>Vitamin/mineral <input type="range" min="0" max="100" value={vitamin} onChange={e=>setVitamin(Number(e.target.value))}/></label><p className="vlab5-observe">Total indikator komposisi: <b>{total}</b>. Simulasi ini untuk membandingkan peran zat gizi, bukan menentukan porsi makan pribadi.</p></div>}
function DigestionTime(){const[tahap,setTahap]=useState(0);const tahapNama=['Mulut','Lambung','Usus halus','Usus besar'];return <div className="vlab5-stage"><div className="vlab5-scene">🍽️ → {['👄','🧪','🌀','🚰'][tahap]}</div><div className="vlab5-controls"><button onClick={()=>setTahap(Math.max(0,tahap-1))}>← Sebelumnya</button><button onClick={()=>setTahap(Math.min(3,tahap+1))}>Berikutnya →</button></div><p className="vlab5-observe">Tahap simulasi: <b>{tahapNama[tahap]}</b>. Ikuti perjalanan makanan dari awal hingga penyerapan/pengolahan lanjutan.</p></div>}
function GrowthSupport(){const[tidur,setTidur]=useState(70);const[nutrisi,setNutrisi]=useState(70);const[gerak,setGerak]=useState(70);const dukung=Math.round((tidur+nutrisi+gerak)/3);return <div className="vlab5-stage"><div className="vlab5-scene">😴 🥗 🏃 → 🌱</div><label>Istirahat cukup <input type="range" min="0" max="100" value={tidur} onChange={e=>setTidur(Number(e.target.value))}/></label><label>Kebiasaan makan beragam <input type="range" min="0" max="100" value={nutrisi} onChange={e=>setNutrisi(Number(e.target.value))}/></label><label>Aktivitas fisik wajar <input type="range" min="0" max="100" value={gerak} onChange={e=>setGerak(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks dukungan kebiasaan sehat pada model: <b>{dukung}</b>. Model tidak menilai ukuran atau bentuk tubuh.</p></div>}

export function VlabKelas5Bab5Screen(){const{labKode}=useParams();const p=VLAB_KELAS5_IPAS_BAB5.find(x=>x.kode===labKode);if(!p)return <main className="halaman-vlab"><Link to={RUTE.vlab}>← Kembali</Link><h1>VLAB tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'breathing-rate':<BreathingRate/>,'lung-volume':<LungVolume/>,'nutrient-balance':<NutrientBalance/>,'digestion-time':<DigestionTime/>,'growth-support':<GrowthSupport/>};return <main className="vlab5-runner"><header><Link to={RUTE.vlab}>←</Link><div><small>IPAS Kelas V · Bab 5 · {p.topik}</small><h1>{p.ikon} {p.nama}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
