import { useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './vlab.css';

export const VLAB_KELAS5_IPAS_BAB6=[
 {kode:'archipelago-model',nama:'Archipelago Model',ikon:'🗺️',topik:'Bagaimana Bentuk Indonesiaku?',tujuan:'Mengamati hubungan jumlah pulau, wilayah daratan, dan perairan pada model sederhana.'},
 {kode:'biodiversity-index',nama:'Biodiversity Index Lab',ikon:'🦜',topik:'Indonesiaku Kaya Hayatinya',tujuan:'Membandingkan keragaman organisme pada beberapa habitat model.'},
 {kode:'habitat-condition',nama:'Habitat Condition Lab',ikon:'🌳',topik:'Indonesiaku Kaya Hayatinya',tujuan:'Mengamati pengaruh kondisi habitat terhadap jumlah jenis yang dapat bertahan pada model.'},
 {kode:'resource-stock',nama:'Resource Stock Lab',ikon:'⛏️',topik:'Indonesiaku Kaya Alamnya',tujuan:'Mengamati perubahan stok sumber daya saat pemakaian dan pemulihan diubah.'},
 {kode:'renewable-flow',nama:'Renewable Flow Lab',ikon:'♻️',topik:'Indonesiaku Kaya Alamnya',tujuan:'Membandingkan sumber daya yang dapat pulih dan yang pulih sangat lambat pada model.'},
] as const;
type Kode=typeof VLAB_KELAS5_IPAS_BAB6[number]['kode'];
function Archipelago(){const[pulau,setPulau]=useState(5);const[air,setAir]=useState(65);return <div className="vlab5-stage"><div className="vlab5-scene">🌊 {'🏝️'.repeat(Math.min(10,pulau))}</div><label>Jumlah pulau model <input type="range" min="1" max="10" value={pulau} onChange={e=>setPulau(Number(e.target.value))}/><b>{pulau}</b></label><label>Proporsi wilayah perairan model <input type="range" min="30" max="90" value={air} onChange={e=>setAir(Number(e.target.value))}/><b>{air}%</b></label><p className="vlab5-observe">Model memperlihatkan negara kepulauan dengan banyak pulau yang dipisahkan dan dihubungkan oleh wilayah perairan.</p></div>}
function Biodiversity(){const[jenis,setJenis]=useState(6);const[seimbang,setSeimbang]=useState(60);const indeks=Math.round(jenis*seimbang/10);return <div className="vlab5-stage"><div className="vlab5-scene">🌿 🐟 🦜 🐒 🌴</div><label>Jumlah jenis <input type="range" min="1" max="12" value={jenis} onChange={e=>setJenis(Number(e.target.value))}/><b>{jenis}</b></label><label>Kemerataan populasi <input type="range" min="10" max="100" value={seimbang} onChange={e=>setSeimbang(Number(e.target.value))}/><b>{seimbang}</b></label><p className="vlab5-observe">Indeks keragaman model: <b>{indeks}</b>. Bandingkan saat jumlah jenis dan kemerataan berubah.</p></div>}
function Habitat(){const[air,setAir]=useState(70);const[vegetasi,setVegetasi]=useState(70);const[gangguan,setGangguan]=useState(20);const dukung=Math.max(0,Math.round((air+vegetasi+(100-gangguan))/3));return <div className="vlab5-stage"><div className="vlab5-scene">🌳 💧 🦜</div><label>Ketersediaan air <input type="range" min="0" max="100" value={air} onChange={e=>setAir(Number(e.target.value))}/></label><label>Tutupan vegetasi <input type="range" min="0" max="100" value={vegetasi} onChange={e=>setVegetasi(Number(e.target.value))}/></label><label>Gangguan habitat <input type="range" min="0" max="100" value={gangguan} onChange={e=>setGangguan(Number(e.target.value))}/></label><p className="vlab5-observe">Indeks dukungan habitat: <b>{dukung}</b>. Kondisi habitat yang baik membantu lebih banyak jenis bertahan pada model.</p></div>}
function ResourceStock(){const[stok,setStok]=useState(100);const[pakai,setPakai]=useState(20);const[pulih,setPulih]=useState(10);const berikut=Math.max(0,Math.min(100,stok-pakai+pulih));return <div className="vlab5-stage"><div className="vlab5-scene">📦 Stok: {stok} → {berikut}</div><label>Pemakaian <input type="range" min="0" max="50" value={pakai} onChange={e=>setPakai(Number(e.target.value))}/></label><label>Pemulihan <input type="range" min="0" max="30" value={pulih} onChange={e=>setPulih(Number(e.target.value))}/></label><button onClick={()=>setStok(berikut)}>Jalankan 1 periode</button><p className="vlab5-observe">Jika pemakaian terus lebih besar daripada pemulihan, stok model akan berkurang.</p></div>}
function Renewable(){const[jenis,setJenis]=useState<'air'|'hutan'|'minyak'>('air');const data={air:{pakai:20,pulih:20},hutan:{pakai:20,pulih:10},minyak:{pakai:20,pulih:0}}[jenis];return <div className="vlab5-stage"><div className="vlab5-components">{(['air','hutan','minyak'] as const).map(x=><button key={x} className={jenis===x?'aktif':''} onClick={()=>setJenis(x)}>{x}</button>)}</div><div className="vlab5-scene">Pemakaian {data.pakai} · Pemulihan model {data.pulih}</div><p className="vlab5-observe">{jenis==='minyak'?'Pada skala waktu manusia, pemulihan minyak bumi sangat lambat.':'Sumber daya ini dapat pulih, tetapi tetap perlu dikelola agar pemakaian tidak melampaui pemulihan.'}</p></div>}
export function VlabKelas5Bab6Screen(){const{labKode}=useParams();const p=VLAB_KELAS5_IPAS_BAB6.find(x=>x.kode===labKode);if(!p)return <main className="halaman-vlab"><Link to={RUTE.vlab}>← Kembali</Link><h1>VLAB tidak ditemukan</h1></main>;const isi:Record<Kode,ReactNode>={'archipelago-model':<Archipelago/>,'biodiversity-index':<Biodiversity/>,'habitat-condition':<Habitat/>,'resource-stock':<ResourceStock/>,'renewable-flow':<Renewable/>};return <main className="vlab5-runner"><header><Link to={RUTE.vlab}>←</Link><div><small>IPAS Kelas V · Bab 6 · {p.topik}</small><h1>{p.ikon} {p.nama}</h1><p>{p.tujuan}</p></div></header>{isi[p.kode]}</main>}
