import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './kelas5-bab2-content.css';

type Jenis='kuis'|'lkpd'|'bank-soal';
const FOKUS=['Mengenali bahwa Bumi dan lingkungan dapat berubah karena proses alam maupun aktivitas manusia.','Mengidentifikasi contoh kerusakan/pencemaran lingkungan dan sumber masalahnya.','Menjelaskan tindakan sederhana yang dapat membantu mengurangi masalah lingkungan.'] as const;
const KUIS=[{q:'Contoh pencemaran udara adalah...',o:['asap kendaraan berlebihan','air jernih','tanah subur','hutan terawat'],a:0},{q:'Sampah yang menyumbat saluran air dapat menyebabkan...',o:['aliran terganggu dan risiko genangan meningkat','cahaya memantul','magnet menguat','bunyi hilang'],a:0},{q:'Tutupan vegetasi pada tanah dapat membantu...',o:['mengurangi limpasan dan erosi','menambah sampah','meningkatkan asap','memutus rangkaian listrik'],a:0},{q:'Tindakan yang lebih tepat untuk sampah adalah...',o:['mengurangi, memilah, dan mengelola dengan benar','membuang ke sungai','membakar sembarangan','meninggalkan di jalan'],a:0},{q:'Masalah lingkungan dapat mengancam kehidupan karena...',o:['mempengaruhi air, udara, tanah, dan makhluk hidup','hanya mengubah warna benda','hanya memengaruhi bunyi','tidak berdampak apa pun'],a:0}];
const PG=['Contoh perubahan lingkungan karena proses alam adalah...','Contoh kerusakan lingkungan akibat aktivitas manusia adalah...','Pencemaran air dapat terjadi karena...','Pencemaran udara dapat terjadi karena...','Sampah yang tidak dikelola dapat...','Ruang hijau dapat membantu...','Vegetasi membantu tanah karena...','Pemilahan sampah bertujuan untuk...','Menjaga sungai dapat dilakukan dengan...','Tindakan siswa yang membantu lingkungan adalah...'];
const JODOH=[['Pencemaran air','masuknya bahan pencemar ke perairan'],['Pencemaran udara','menurunnya kualitas udara'],['Sampah','sisa kegiatan yang perlu dikelola'],['Erosi','pengikisan tanah'],['Vegetasi','membantu melindungi tanah'],['Ruang hijau','area tumbuhan di lingkungan'],['Pemilahan','memisahkan sampah berdasarkan jenis'],['Daur ulang','mengolah bahan menjadi produk baru'],['Konservasi','upaya menjaga lingkungan/sumber daya'],['Gotong royong','kerja bersama menjaga lingkungan']];
const ESAI=['Jelaskan satu contoh perubahan lingkungan akibat proses alam.','Jelaskan satu contoh kerusakan lingkungan akibat aktivitas manusia.','Mengapa sampah yang tidak dikelola dapat menimbulkan masalah?','Tuliskan dua cara menjaga kualitas air atau udara di sekitar sekolah.','Buat satu rencana sederhana kegiatan kelas untuk membantu menjaga lingkungan.'];
function Kuis(){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=KUIS[Math.min(i,KUIS.length-1)];if(i>=KUIS.length)return <section className="k5-content-card"><h2>Kuis selesai</h2><div className="k5-score">{skor}/{KUIS.length*100}</div><button onClick={()=>{setI(0);setSkor(0)}}>Ulangi</button></section>;return <section className="k5-content-card"><p className="k5-kicker">Soal {i+1}/{KUIS.length}</p><h2>{x.q}</h2><div className="k5-options">{x.o.map((o,n)=><button key={o} onClick={()=>{if(n===x.a)setSkor(skor+100);setI(i+1)}}>{String.fromCharCode(65+n)}. {o}</button>)}</div></section>}
function Lkpd(){return <section className="k5-worksheet"><div className="k5-worksheet__banner">🌍 ♻️ LKPD IPAS KELAS V 💧 🌳</div><h2>Bab 8 — Bumiku Sayang, Bumiku Malang</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid"><article><h3>🔎 Aktivitas 1 · Detektif Lingkungan</h3><p>Amati lingkungan sekolah. Temukan satu kondisi yang sudah baik dan satu yang perlu diperbaiki.</p><p>Sudah baik: ______________________________</p><p>Perlu diperbaiki: __________________________</p></article><article><h3>💧 Aktivitas 2 · Kualitas Air</h3><p>Gunakan VLAB Water Quality. Catat perubahan indeks saat limbah dan pengelolaan diubah.</p><table><tbody><tr><th>Kondisi</th><th>Indeks</th></tr><tr><td>Limbah rendah</td><td>_____</td></tr><tr><td>Limbah tinggi</td><td>_____</td></tr><tr><td>Pengelolaan tinggi</td><td>_____</td></tr></tbody></table></article><article><h3>♻️ Aktivitas 3 · Alur Sampah</h3><p>Tuliskan contoh pemilahan sampah yang dapat dilakukan di kelas.</p><p>Organik: _________________________________</p><p>Anorganik: _______________________________</p></article><article><h3>🌳 Refleksi</h3><p>Tuliskan dua tindakan yang bisa dilakukan bersama teman untuk menjaga lingkungan.</p><p>1. ______________________________________________</p><p>2. ______________________________________________</p></article></div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank(){return <section className="k5-bank"><h2>Bank Soal IPAS Kelas V · Bab 8</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{PG.map((q,i)=><li key={q}><b>{q}</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><div className="k5-match">{JODOH.map(([a,b],i)=><div key={a}><b>{i+1}. {a}</b><span>↔</span><span>{b}</span></div>)}</div><h3>C. Esai</h3><ol>{ESAI.map(q=><li key={q}>{q}<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5Bab8ContentScreen(){const path=useLocation().pathname;const jenis:Jenis=path.includes('bank-soal')?'bank-soal':path.includes('lkpd')?'lkpd':'kuis';return <main className="k5-content"><header className="k5-content__header"><Link to={RUTE.dasbor}>←</Link><div><small>IPAS Kelas V · Buku Referensi · Bab 8</small><h1>{jenis==='kuis'?'⚡ Kuis Langsung':jenis==='lkpd'?'🎨 LKPD Interaktif':'📚 Bank Soal'}</h1><p>Bumiku Sayang, Bumiku Malang</p></div></header><aside className="k5-tujuan"><b>Fokus belajar Bab 8</b>{FOKUS.map(x=><span key={x}>• {x}</span>)}</aside>{jenis==='kuis'?<Kuis/>:jenis==='lkpd'?<Lkpd/>:<Bank/>}</main>}
