import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BAB_MASTER_KELAS5, BUKU_MASTER_KELAS5, TOPIK_MASTER_KELAS5 } from '../../lib/referensi/kelas5MasterSeed';
import './kelas5-bab2-content.css';

type Mode='hub'|'game'|'vlab'|'kuis'|'lkpd'|'bank-soal';
const LABEL:Record<string,string>={MAT:'Matematika',PP:'Pendidikan Pancasila',BI:'Bahasa Indonesia',BING:'Bahasa Inggris',KKA:'Koding dan Kecerdasan Artifisial',RUPA:'Seni Rupa'};
const IKON:Record<string,string>={MAT:'🔢',PP:'🇮🇩',BI:'📖',BING:'🌏',KKA:'💻',RUPA:'🎨'};
const GAME:Record<string,string[]>={MAT:['🎯 Target Angka','🧩 Susun Bilangan','⚡ Hitung Kilat','📐 Tantangan Bentuk','🏆 Math Boss'],PP:['⚖️ Pilih Sikap','🤝 Misi Musyawarah','🇮🇩 Jelajah Pancasila','🧩 Pasangkan Nilai','🏆 Warga Teladan'],BI:['📝 Susun Kalimat','🔎 Detektif Teks','📚 Jelajah Kosakata','🎭 Tebak Makna','🏆 Editor Cilik'],BING:['🔤 Word Match','🗣️ Speak & Choose','🧩 Sentence Builder','🗺️ English Quest','🏆 Vocabulary Rush']};
function cari(mapel:string,babNo:string){const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);const bab=buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id).find(x=>String(x.nomor_tampil).toLowerCase()===babNo.toLowerCase()||String(x.id).endsWith(`-${babNo}`)):undefined;return{buku,bab,topik:bab?TOPIK_MASTER_KELAS5.filter(x=>x.bab_id===bab.id):[]}}
function GameStage({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const daftar=GAME[mapel]||['🎯 Tantangan Topik','🧩 Susun Konsep','⚡ Tantangan Cepat','🗺️ Jelajah Materi','🏆 Misi Juara'];const[m,setM]=useState(0),[skor,setSkor]=useState(0),[ronde,setRonde]=useState(0),[combo,setCombo]=useState(0);const fokus=topik.length?topik[ronde%topik.length]:judul;const aksi=(benar:boolean)=>{setSkor(s=>Math.max(0,s+(benar?100+combo*20:-25)));setCombo(c=>benar?c+1:0);setRonde(r=>r+1)};return <section className="k5-content-card"><p className="k5-kicker">Game {LABEL[mapel]} · Ronde {ronde+1}</p><h2>{daftar[m]}</h2><div className="k5-options">{daftar.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{x}</button>)}</div><div className="k5-score">⭐ {skor} &nbsp; 🔥 Combo {combo}</div><h3>{fokus}</h3><p>{mapel==='MAT'?'Gunakan papan/alat hitung untuk menemukan penyelesaian, lalu validasi hasil.':mapel==='PP'?'Pilih tindakan yang paling sesuai dengan nilai atau konsep pada topik ini dan jelaskan alasannya.':mapel==='BI'?'Temukan kata kunci, susun gagasan, lalu jelaskan isi topik dengan kalimatmu sendiri.':mapel==='BING'?'Read the topic, identify key words, then explain or demonstrate the meaning.':'Selesaikan misi berdasarkan topik buku.'}</p><div className="k5-options"><button onClick={()=>aksi(true)}>✓ Berhasil</button><button onClick={()=>aksi(false)}>↻ Coba tantangan berikut</button></div></section>}
function LabStage({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const[fokus,setFokus]=useState(0),[a,setA]=useState(25),[b,setB]=useState(4);const t=topik.length?topik[fokus%topik.length]:judul;if(mapel==='MAT')return <section className="k5-content-card"><p className="k5-kicker">Manipulatif Matematika</p><h2>{t}</h2><label>Bilangan A: <b>{a}</b><input type="range" min="1" max="100" value={a} onChange={e=>setA(+e.target.value)}/></label><label>Bilangan B: <b>{b}</b><input type="range" min="1" max="20" value={b} onChange={e=>setB(+e.target.value)}/></label><div className="k5-score">A + B = {a+b} · A − B = {a-b} · A × B = {a*b}</div><div className="k5-options"><button onClick={()=>setFokus(f=>f+1)}>Topik berikut →</button></div></section>;
if(mapel==='PP')return <section className="k5-content-card"><p className="k5-kicker">Simulasi Keputusan</p><h2>{t}</h2><p>Bayangkan situasi di kelas/lingkungan yang berkaitan dengan topik ini. Pilih cara mengambil keputusan.</p><div className="k5-options"><button onClick={()=>setA(100)}>🤝 Musyawarah</button><button onClick={()=>setA(60)}>🙋 Pendapat pribadi</button><button onClick={()=>setA(30)}>⚡ Bertindak tanpa diskusi</button></div><div className="k5-score">Indikator kolaborasi: {a}%</div><button onClick={()=>setFokus(f=>f+1)}>Skenario berikut →</button></section>;
if(mapel==='BI'||mapel==='BING')return <section className="k5-content-card"><p className="k5-kicker">Laboratorium Bahasa</p><h2>{t}</h2><p>{mapel==='BING'?'Build, read, and explain a sentence related to this unit.':'Bangun kalimat, tentukan kata kunci, lalu jelaskan gagasan utamanya.'}</p><textarea rows={5} placeholder={mapel==='BING'?'Write your sentence here…':'Tulis kalimat atau gagasan di sini…'} /><div className="k5-options"><button onClick={()=>setFokus(f=>f+1)}>Topik berikut →</button></div></section>;
return <section className="k5-content-card"><h2>{t}</h2><p>Simulasi khusus mapel ini menunggu struktur bab/topik dari buku referensi agar tidak dibuat berdasarkan tebakan.</p></section>}
function Kuis({mapel,topik}:{mapel:string;topik:string[]}){const[i,setI]=useState(0),[skor,setSkor]=useState(0);const fokus=topik.length?topik[i%topik.length]:'materi bab';return <section className="k5-content-card"><p className="k5-kicker">Kuis {LABEL[mapel]} · {i+1}</p><h2>{fokus}</h2><p>{mapel==='MAT'?'Tunjukkan cara menyelesaikan contoh dari topik ini.':mapel==='PP'?'Berikan contoh penerapan konsep ini dalam kehidupan sehari-hari.':mapel==='BI'?'Jelaskan gagasan penting dan contoh penggunaan bahasanya.':mapel==='BING'?'Explain the key idea and give an example from the lesson.':'Jelaskan konsep berdasarkan buku.'}</p><div className="k5-options"><button onClick={()=>{setSkor(s=>s+100);setI(n=>n+1)}}>✓ Terjawab</button><button onClick={()=>setI(n=>n+1)}>Lewati</button></div><div className="k5-score">Skor {skor}</div></section>}
function Lkpd({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){return <section className="k5-worksheet"><div className="k5-worksheet__banner">{IKON[mapel]} ✨ LKPD {LABEL[mapel]?.toUpperCase()} KELAS V ✨</div><h2>{judul}</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid">{(topik.length?topik:[judul]).slice(0,5).map((t,i)=><article key={t}><h3>{IKON[mapel]} Aktivitas {i+1}</h3><strong>{t}</strong><p>{mapel==='MAT'?'Tuliskan strategi, proses hitung, dan kesimpulanmu.':mapel==='PP'?'Tuliskan contoh sikap/tindakan dan alasanmu.':mapel==='BI'?'Tuliskan kata kunci, gagasan, dan contoh kalimatmu.':mapel==='BING'?'Write key words, a sentence, and its meaning.':'Kerjakan berdasarkan buku referensi.'}</p><p>__________________________________________________</p><p>__________________________________________________</p></article>)}</div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const f=topik.length?topik:[judul];return <section className="k5-bank"><h2>Bank Soal · {LABEL[mapel]} · {judul}</h2><p>25 butir: 10 pilihan ganda · 10 menjodohkan · 5 esai. Kisi-kisi mengikuti topik buku; butir final tetap harus bersumber dari isi buku, bukan judul topik saja.</p><h3>A. Pilihan Ganda</h3><ol>{Array.from({length:10},(_,i)=><li key={i}><b>{f[i%f.length]}</b> — soal berbasis materi buku.<div className="k5-lines">A. ______ B. ______ C. ______ D. ______</div></li>)}</ol><h3>B. Menjodohkan</h3><ol>{Array.from({length:10},(_,i)=><li key={i}>{f[i%f.length]} ↔ ____________________</li>)}</ol><h3>C. Esai</h3><ol>{Array.from({length:5},(_,i)=><li key={i}>Jelaskan “{f[i%f.length]}” berdasarkan pembelajaran dari buku.<div className="k5-answer-lines">________________________________________<br/>________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5MapelMasterScreen(){const{mapelKode='',babNo='',mode='hub'}=useParams();const mapel=mapelKode.toUpperCase();const d=useMemo(()=>cari(mapel,babNo),[mapel,babNo]);const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);const list=buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id):[];if(!buku)return <main className="k5-content"><h1>Referensi mapel belum tersedia</h1></main>;if(mode==='hub'||!babNo)return <main className="k5-content"><header className="k5-content__header"><div><small>Kelas V · Buku Referensi</small><h1>{IKON[mapel]} {LABEL[mapel]}</h1><p>{buku.judul} · {buku.penerbit}</p></div></header>{list.length?<section className="k5-lkpd-grid">{list.map(b=><article key={b.id}><h3>{b.nomor_tampil} · {b.judul_bab}</h3><p>{TOPIK_MASTER_KELAS5.filter(t=>t.bab_id===b.id).map(t=>t.judul_topik).join(' · ')||'Topik rinci menunggu isi buku.'}</p><div className="k5-options">{(['game','vlab','kuis','lkpd','bank-soal'] as Mode[]).map(m=><Link key={m} className="k5-primary" to={`/kelas5/${mapel}/${b.nomor_tampil}/${m}`}>{m}</Link>)}</div></article>)}</section>:<section className="k5-content-card"><h2>Struktur bab belum tersedia</h2><p>Buku sudah tercatat, tetapi isi bab/topik belum tersedia. Aplikasi tidak mengarang konten.</p></section>}</main>;if(!d.bab)return <main className="k5-content"><h1>Bab tidak ditemukan</h1></main>;const topik=d.topik.map(x=>x.judul_topik);return <main className="k5-content"><header className="k5-content__header"><Link to={`/kelas5/${mapel}`}>←</Link><div><small>{LABEL[mapel]} Kelas V · {buku.judul}</small><h1>{d.bab.nomor_tampil} · {d.bab.judul_bab}</h1></div></header>{mode==='game'?<GameStage mapel={mapel} judul={d.bab.judul_bab} topik={topik}/>:mode==='vlab'?<LabStage mapel={mapel} judul={d.bab.judul_bab} topik={topik}/>:mode==='kuis'?<Kuis mapel={mapel} topik={topik}/>:mode==='lkpd'?<Lkpd mapel={mapel} judul={d.bab.judul_bab} topik={topik}/>:<Bank mapel={mapel} judul={d.bab.judul_bab} topik={topik}/>}</main>}
