import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './kelas5-bab2-content.css';

type Jenis='kuis'|'lkpd'|'bank-soal';
const FOKUS=['Mengenali beragam bentuk permukaan Bumi dan kenampakan alam.','Menjelaskan bahwa permukaan Bumi dapat berubah karena proses alam.','Menghubungkan contoh perubahan permukaan Bumi dengan hasil pengamatan atau simulasi sederhana.'] as const;
const KUIS=[{q:'Batas antara daratan dan laut disebut...',o:['pantai','gunung','lembah','sungai'],a:0},{q:'Tanah di lereng yang terbawa aliran air merupakan contoh...',o:['erosi','pemantulan','konduksi listrik','getaran bunyi'],a:0},{q:'Endapan dapat terbentuk ketika...',o:['material yang terbawa kehilangan energi dan mengendap','cahaya dipantulkan','magnet ditolak','bunyi merambat'],a:0},{q:'Vegetasi di lereng dapat membantu...',o:['mengurangi erosi','menambah pembiasan','menghilangkan gravitasi','membuat listrik'],a:0},{q:'Permukaan Bumi dapat berubah karena...',o:['proses alam yang berlangsung dari waktu ke waktu','warna langit saja','bunyi kendaraan saja','arah cahaya saja'],a:0}];
const PG=['Contoh kenampakan daratan adalah...','Contoh kenampakan perairan adalah...','Aliran air yang mengikis tanah disebut...','Material hasil erosi dapat berpindah karena...','Endapan biasanya terjadi ketika...','Tutupan vegetasi pada lereng cenderung...','Perubahan suhu berulang dapat membuat batu...','Gunung api merupakan contoh proses yang dapat...','Getaran gempa dapat merambat melalui...','Cara belajar yang tepat tentang perubahan Bumi adalah...'];
const JODOH=[['Pantai','batas daratan dan laut'],['Sungai','aliran air di permukaan'],['Pegunungan','wilayah daratan tinggi'],['Erosi','pengikisan dan pemindahan material'],['Sedimentasi','pengendapan material'],['Vegetasi','membantu melindungi tanah'],['Pelapukan','pemecahan batuan'],['Gunung api','salah satu proses pembentuk/perubah permukaan'],['Getaran','dapat merambat melalui medium'],['Bentang alam','bentuk permukaan Bumi']];
const ESAI=['Jelaskan dua contoh bentuk permukaan Bumi yang ada di sekitar atau yang pernah kamu lihat.','Jelaskan bagaimana hujan dapat menyebabkan perubahan pada lereng tanah.','Mengapa vegetasi dapat membantu mengurangi erosi?','Jelaskan perbedaan erosi dan sedimentasi dengan bahasamu sendiri.','Tuliskan satu contoh perubahan permukaan Bumi dan jelaskan proses yang terlibat.'];
function Kuis(){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=KUIS[Math.min(i,KUIS.length-1)];if(i>=KUIS.length)return <section className="k5-content-card"><h2>Kuis selesai</h2><div className="k5-score">{skor}/{KUIS.length*100}</div><button onClick={()=>{setI(0);setSkor(0)}}>Ulangi</button></section>;return <section className="k5-content-card"><p className="k5-kicker">Soal {i+1}/{KUIS.length}</p><h2>{x.q}</h2><div className="k5-options">{x.o.map((o,n)=><button key={o} onClick={()=>{if(n===x.a)setSkor(skor+100);setI(i+1)}}>{String.fromCharCode(65+n)}. {o}</button>)}</div></section>}
function Lkpd(){return <section className="k5-worksheet"><div className="k5-worksheet__banner">🌍 ⛰️ LKPD IPAS KELAS V 🌧️ 🌋</div><h2>Bab 4 — Ayo Berkenalan dengan Bumi Kita</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid"><article><h3>🗺️ Aktivitas 1 · Bentang Alam</h3><p>Tuliskan tiga bentuk permukaan Bumi yang kamu ketahui dan cirinya.</p><p>1. __________ : __________________________</p><p>2. __________ : __________________________</p><p>3. __________ : __________________________</p></article><article><h3>🌧️ Aktivitas 2 · Erosi Model</h3><p>Gunakan VLAB Slope Erosion. Bandingkan saat hujan dan kemiringan diubah.</p><table><tbody><tr><th>Kondisi</th><th>Indeks erosi</th></tr><tr><td>Hujan rendah</td><td>__________</td></tr><tr><td>Hujan tinggi</td><td>__________</td></tr><tr><td>Vegetasi tinggi</td><td>__________</td></tr></tbody></table></article><article><h3>🏞️ Aktivitas 3 · Sedimen</h3><p>Ubah kecepatan arus dan ukuran sedimen pada VLAB. Apa yang kamu amati?</p><p>__________________________________________________</p></article><article><h3>💭 Refleksi</h3><p>Mengapa permukaan Bumi dapat berubah dari waktu ke waktu?</p><p>__________________________________________________</p><p>__________________________________________________</p></article></div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank(){return <section className="k5-bank"><h2>Bank Soal IPAS Kelas V · Bab 4</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{PG.map((q,i)=><li key={q}><b>{q}</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><div className="k5-match">{JODOH.map(([a,b],i)=><div key={a}><b>{i+1}. {a}</b><span>↔</span><span>{b}</span></div>)}</div><h3>C. Esai</h3><ol>{ESAI.map(q=><li key={q}>{q}<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5Bab4ContentScreen(){const path=useLocation().pathname;const jenis:Jenis=path.includes('bank-soal')?'bank-soal':path.includes('lkpd')?'lkpd':'kuis';return <main className="k5-content"><header className="k5-content__header"><Link to={RUTE.dasbor}>←</Link><div><small>IPAS Kelas V · Buku Referensi · Bab 4</small><h1>{jenis==='kuis'?'⚡ Kuis Langsung':jenis==='lkpd'?'🎨 LKPD Interaktif':'📚 Bank Soal'}</h1><p>Ayo Berkenalan dengan Bumi Kita</p></div></header><aside className="k5-tujuan"><b>Fokus belajar Bab 4</b>{FOKUS.map(x=><span key={x}>• {x}</span>)}</aside>{jenis==='kuis'?<Kuis/>:jenis==='lkpd'?<Lkpd/>:<Bank/>}</main>}
