import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BAB_MASTER_KELAS5, BUKU_MASTER_KELAS5, TOPIK_MASTER_KELAS5 } from '../../lib/referensi/kelas5MasterSeed';
import './kelas5-bab2-content.css';

type Mode='hub'|'game'|'vlab'|'kuis'|'lkpd'|'bank-soal';
const MAPEL_LABEL:Record<string,string>={MAT:'Matematika',PP:'Pendidikan Pancasila',BI:'Bahasa Indonesia',BING:'Bahasa Inggris',KKA:'Koding dan Kecerdasan Artifisial',RUPA:'Seni Rupa'};
const IKON:Record<string,string>={MAT:'🔢',PP:'🇮🇩',BI:'📖',BING:'🌏',KKA:'💻',RUPA:'🎨'};

function data(mapel:string,babNo:string){const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);const bab=buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id).find(x=>String(x.nomor_tampil).toLowerCase()===babNo.toLowerCase()||String(x.id).endsWith(`-${babNo}`)):undefined;const topik=bab?TOPIK_MASTER_KELAS5.filter(x=>x.bab_id===bab.id):[];return{buku,bab,topik}}
function Game({judul,topik}:{judul:string;topik:string[]}){const[mode,setMode]=useState(0);const[skor,setSkor]=useState(0);const[putaran,setPutaran]=useState(0);const mekanik=['🎯 Target Cepat','🧩 Susun Konsep','⚡ Pilih Kilat','🗺️ Jelajah Materi','🏆 Tantangan Juara'];const item=topik.length?topik[putaran%topik.length]:judul;return <section className="k5-content-card"><h2>{mekanik[mode]}</h2><p>Materi: <b>{item}</b></p><div className="k5-options">{mekanik.map((m,i)=><button key={m} onClick={()=>setMode(i)}>{m}</button>)}</div><div className="k5-score">Skor {skor}</div><p>Selesaikan tantangan berdasarkan konsep pada topik yang tampil.</p><div className="k5-options"><button onClick={()=>{setSkor(s=>s+100);setPutaran(p=>p+1)}}>✓ Tepat / Lanjut</button><button onClick={()=>setPutaran(p=>p+1)}>Lewati</button></div></section>}
function Vlab({judul,topik}:{judul:string;topik:string[]}){const[mode,setMode]=useState(0);const[a,setA]=useState(50);const[b,setB]=useState(50);const labs=['🔬 Eksplorasi','🎛️ Ubah Variabel','📊 Bandingkan','🧪 Uji Skenario','🔎 Amati Pola'];const fokus=topik.length?topik[mode%topik.length]:judul;return <section className="k5-content-card"><h2>{labs[mode]} · {fokus}</h2><div className="k5-options">{labs.map((x,i)=><button key={x} onClick={()=>setMode(i)}>{x}</button>)}</div><label>Variabel A <input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)}/></label><label>Variabel B <input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)}/></label><div className="k5-score">Hasil pengamatan: {Math.round((a+b)/2)}</div><p>Bandingkan perubahan hasil ketika kedua variabel digeser. Gunakan hasil sebagai bahan diskusi, bukan sebagai pengganti isi buku.</p></section>}
function Kuis({topik}:{topik:string[]}){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const fokus=topik.length?topik[i%topik.length]:'materi bab';return <section className="k5-content-card"><p className="k5-kicker">Kuis Langsung · soal {i+1}</p><h2>Manakah pernyataan yang paling sesuai dengan topik “{fokus}”?</h2><div className="k5-options"><button onClick={()=>{setSkor(s=>s+100);setI(n=>n+1)}}>Saya dapat menjelaskan konsep dan memberi contoh dari buku</button><button onClick={()=>setI(n=>n+1)}>Saya masih perlu membaca ulang bagian ini</button></div><div className="k5-score">Skor {skor}</div></section>}
function Lkpd({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){return <section className="k5-worksheet"><div className="k5-worksheet__banner">{IKON[mapel]} ✨ LKPD {MAPEL_LABEL[mapel]?.toUpperCase()} KELAS V ✨</div><h2>{judul}</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid">{(topik.length?topik:[judul]).slice(0,5).map((t,i)=><article key={t}><h3>Aktivitas {i+1} · {t}</h3><p>Tuliskan hasil pengamatan, contoh, atau penyelesaian berdasarkan pembelajaran dan buku referensi.</p><p>__________________________________________________</p><p>__________________________________________________</p></article>)}</div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank({judul,topik}:{judul:string;topik:string[]}){const fokus=topik.length?topik:[judul];return <section className="k5-bank"><h2>Bank Soal · {judul}</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{Array.from({length:10},(_,i)=><li key={i}><b>{fokus[i%fokus.length]} — pilih jawaban yang paling tepat berdasarkan materi buku.</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><ol>{Array.from({length:10},(_,i)=><li key={i}>{fokus[i%fokus.length]} ↔ ____________________</li>)}</ol><h3>C. Esai</h3><ol>{Array.from({length:5},(_,i)=><li key={i}>Jelaskan dengan bahasamu sendiri konsep “{fokus[i%fokus.length]}” dan berikan contoh sesuai buku.<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5MapelMasterScreen(){const{mapelKode='',babNo='',mode='hub'}=useParams();const mapel=mapelKode.toUpperCase();const d=useMemo(()=>data(mapel,babNo),[mapel,babNo]);const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);const babList=buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id):[];if(!buku)return <main className="k5-content"><h1>Referensi mapel belum tersedia</h1></main>;if(mode==='hub'||!babNo){return <main className="k5-content"><header className="k5-content__header"><div><small>Kelas V · Buku Referensi Nyata</small><h1>{IKON[mapel]} {MAPEL_LABEL[mapel]||mapel}</h1><p>{buku.judul} · {buku.penerbit}</p></div></header>{babList.length?<section className="k5-lkpd-grid">{babList.map(b=><article key={b.id}><h3>{b.nomor_tampil} · {b.judul_bab}</h3><p>{TOPIK_MASTER_KELAS5.filter(t=>t.bab_id===b.id).map(t=>t.judul_topik).join(' · ')||'Topik rinci menunggu data buku.'}</p><div className="k5-options">{(['game','vlab','kuis','lkpd','bank-soal'] as Mode[]).map(m=><Link key={m} className="k5-primary" to={`/kelas5/${mapel}/${b.nomor_tampil}/${m}`}>{m}</Link>)}</div></article>)}</section>:<section className="k5-content-card"><h2>Struktur bab belum tersedia</h2><p>Buku sudah tercatat sebagai referensi, tetapi isi/bab belum tersedia di sumber yang sudah dimasukkan. Konten tidak dibuat dengan mengarang.</p></section>}</main>};if(!d.bab)return <main className="k5-content"><h1>Bab tidak ditemukan</h1></main>;const topik=d.topik.map(x=>x.judul_topik);return <main className="k5-content"><header className="k5-content__header"><Link to={`/kelas5/${mapel}`}>←</Link><div><small>{MAPEL_LABEL[mapel]} Kelas V · {buku.judul}</small><h1>{d.bab.nomor_tampil} · {d.bab.judul_bab}</h1></div></header>{mode==='game'?<Game judul={d.bab.judul_bab} topik={topik}/>:mode==='vlab'?<Vlab judul={d.bab.judul_bab} topik={topik}/>:mode==='kuis'?<Kuis topik={topik}/>:mode==='lkpd'?<Lkpd mapel={mapel} judul={d.bab.judul_bab} topik={topik}/>:<Bank judul={d.bab.judul_bab} topik={topik}/>}</main>}
