import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BAB_MASTER_KELAS5, BUKU_MASTER_KELAS5, TOPIK_MASTER_KELAS5 } from '../../lib/referensi/kelas5MasterSeed';
import { LINGKUP_KKA_RUPA_KELAS5 } from '../../lib/referensi/kelas5KkaRupaSupplement';
import './kelas5-bab2-content.css';

type Mode='hub'|'game'|'vlab'|'kuis'|'lkpd'|'bank-soal';
const LABEL:Record<string,string>={MAT:'Matematika',PP:'Pendidikan Pancasila',BI:'Bahasa Indonesia',BING:'Bahasa Inggris',KKA:'Koding dan Kecerdasan Artifisial',RUPA:'Seni Rupa'};
const IKON:Record<string,string>={MAT:'🔢',PP:'🇮🇩',BI:'📖',BING:'🌏',KKA:'💻',RUPA:'🎨'};
const GAME:Record<string,string[]>={MAT:['🎯 Target Angka','🧩 Susun Bilangan','⚡ Hitung Kilat','📐 Tantangan Bentuk','🏆 Math Boss'],PP:['⚖️ Pilih Sikap','🤝 Misi Musyawarah','🇮🇩 Jelajah Pancasila','🧩 Pasangkan Nilai','🏆 Warga Teladan'],BI:['📝 Susun Kalimat','🔎 Detektif Teks','📚 Jelajah Kosakata','🎭 Tebak Makna','🏆 Editor Cilik'],BING:['🔤 Word Match','🗣️ Speak & Choose','🧩 Sentence Builder','🗺️ English Quest','🏆 Vocabulary Rush'],KKA:['🤖 Robot Instruksi','🧩 Pecahkan Masalah','🔐 Penjaga Data','🧠 AI atau Bukan?','🎯 Klasifikasi Pintar'],RUPA:['🎨 Mix & Match Warna','🧩 Susun Komposisi','🌺 Ragam Hias Hunt','✏️ Studio Ekspresi','🏆 Kurator Cilik']};

function sumberData(mapel:string,babNo:string){
 const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);
 const ekstra=LINGKUP_KKA_RUPA_KELAS5.filter(x=>x.mapel===mapel);
 if(ekstra.length){const item=ekstra.find(x=>x.nomor.toLowerCase()===decodeURIComponent(babNo).toLowerCase()||x.id===babNo);return{buku,bab:item?{id:item.id,nomor_tampil:item.nomor,judul_bab:item.judul}:undefined,topik:item?.topik||[],sumber:item?.sumber||''}}
 const bab=buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id).find(x=>String(x.nomor_tampil).toLowerCase()===babNo.toLowerCase()||String(x.id).endsWith(`-${babNo}`)):undefined;
 return{buku,bab,topik:bab?TOPIK_MASTER_KELAS5.filter(x=>x.bab_id===bab.id).map(x=>x.judul_topik):[],sumber:buku?.judul||''};
}

function GameStage({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const daftar=GAME[mapel]||['🎯 Tantangan','🧩 Susun','⚡ Cepat','🗺️ Jelajah','🏆 Juara'];const[m,setM]=useState(0),[skor,setSkor]=useState(0),[ronde,setRonde]=useState(0),[combo,setCombo]=useState(0);const fokus=topik[ronde%Math.max(1,topik.length)]||judul;const aksi=(ok:boolean)=>{setSkor(s=>Math.max(0,s+(ok?100+combo*20:-25)));setCombo(c=>ok?c+1:0);setRonde(r=>r+1)};const instruksi=mapel==='KKA'?'Susun langkah, kenali pola, jaga data pribadi, atau klasifikasikan contoh sesuai misi.':mapel==='RUPA'?'Amati unsur rupa, pilih komposisi/warna/pola, lalu selesaikan tantangan visual.':mapel==='MAT'?'Gunakan strategi hitung atau manipulatif untuk menyelesaikan misi.':mapel==='PP'?'Pilih tindakan yang sesuai nilai dan jelaskan alasannya.':mapel==='BI'?'Temukan kata kunci dan susun gagasan dengan bahasamu sendiri.':'Read, choose key words, and complete the language mission.';return <section className="k5-content-card"><p className="k5-kicker">Game {LABEL[mapel]} · Ronde {ronde+1}</p><h2>{daftar[m]}</h2><div className="k5-options">{daftar.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{x}</button>)}</div><div className="k5-score">⭐ {skor} · 🔥 Combo {combo}</div><h3>{fokus}</h3><p>{instruksi}</p><div className="k5-options"><button onClick={()=>aksi(true)}>✓ Misi berhasil</button><button onClick={()=>aksi(false)}>↻ Tantangan berikut</button></div></section>}

function LabStage({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const[i,setI]=useState(0),[a,setA]=useState(40),[b,setB]=useState(60);const t=topik[i%Math.max(1,topik.length)]||judul;if(mapel==='KKA')return <section className="k5-content-card"><p className="k5-kicker">💻 Lab Koding & KA</p><h2>{t}</h2><div className="k5-options"><button onClick={()=>setA(x=>Math.min(100,x+20))}>➕ Tambah data/pola</button><button onClick={()=>setA(x=>Math.max(0,x-20))}>➖ Kurangi data/pola</button><button onClick={()=>setB(x=>100-x)}>🔄 Ubah aturan</button></div><div className="k5-score">Input {a}% · Kecocokan aturan {b}% · Prediksi {Math.round((a+b)/2)}%</div><p>Ubah input dan aturan, lalu amati bagaimana hasil klasifikasi/prediksi ikut berubah. Untuk materi keamanan digital, gunakan skenario tanpa memasukkan data pribadi sungguhan.</p><button onClick={()=>setI(x=>x+1)}>Eksperimen berikut →</button></section>;
if(mapel==='RUPA')return <section className="k5-content-card"><p className="k5-kicker">🎨 Studio Seni Interaktif</p><h2>{t}</h2><label>Keseimbangan komposisi <input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)}/></label><label>Intensitas/kontras visual <input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)}/></label><div style={{minHeight:160,borderRadius:18,margin:'16px 0',display:'grid',placeItems:'center',fontSize:48,background:`linear-gradient(${a+45}deg, hsl(${a*3.6} 70% 70%), hsl(${b*3.6} 70% 55%))`}}>◼︎ ● ▲ ✦</div><div className="k5-score">Komposisi {a}% · Kontras {b}%</div><p>Geser kontrol, amati perubahan warna dan keseimbangan, lalu jelaskan pilihan visualmu.</p><button onClick={()=>setI(x=>x+1)}>Eksplorasi berikut →</button></section>;
if(mapel==='MAT')return <section className="k5-content-card"><h2>Manipulatif · {t}</h2><label>A: {a}<input type="range" min="1" max="100" value={a} onChange={e=>setA(+e.target.value)}/></label><label>B: {b}<input type="range" min="1" max="100" value={b} onChange={e=>setB(+e.target.value)}/></label><div className="k5-score">A+B={a+b} · A−B={a-b}</div></section>;
return <section className="k5-content-card"><h2>Aktivitas Interaktif · {t}</h2><textarea rows={5} placeholder="Tulis hasil pengamatan/latihan di sini…"/><button onClick={()=>setI(x=>x+1)}>Aktivitas berikut →</button></section>}

function Kuis({mapel,topik}:{mapel:string;topik:string[]}){const[i,setI]=useState(0),[skor,setSkor]=useState(0);const f=topik[i%Math.max(1,topik.length)]||'materi';return <section className="k5-content-card"><p className="k5-kicker">Kuis {LABEL[mapel]} · {i+1}</p><h2>{f}</h2><p>{mapel==='KKA'?'Jelaskan konsep dan pilih penerapan yang aman/logis.':mapel==='RUPA'?'Identifikasi unsur/prinsip rupa dan jelaskan pilihan visualmu.':'Jawab berdasarkan materi pembelajaran.'}</p><div className="k5-options"><button onClick={()=>{setSkor(s=>s+100);setI(x=>x+1)}}>✓ Terjawab</button><button onClick={()=>setI(x=>x+1)}>Lewati</button></div><div className="k5-score">Skor {skor}</div></section>}
function Lkpd({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){return <section className="k5-worksheet"><div className="k5-worksheet__banner">{IKON[mapel]} ✨ LKPD {LABEL[mapel]?.toUpperCase()} KELAS V ✨</div><h2>{judul}</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid">{topik.slice(0,5).map((t,i)=><article key={t}><h3>{IKON[mapel]} Aktivitas {i+1}</h3><strong>{t}</strong><p>{mapel==='KKA'?'Pecahkan misi secara runtut, tuliskan langkah/aturan, lalu refleksikan hasilnya.':mapel==='RUPA'?'Buat sketsa/eksperimen visual, tentukan unsur rupa yang dipakai, lalu ceritakan prosesnya.':'Kerjakan aktivitas sesuai materi.'}</p><p>__________________________________________________</p><p>__________________________________________________</p></article>)}</div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank({mapel,judul,topik}:{mapel:string;judul:string;topik:string[]}){const f=topik.length?topik:[judul];return <section className="k5-bank"><h2>Bank Soal · {LABEL[mapel]} · {judul}</h2><p>25 butir: 10 pilihan ganda · 10 menjodohkan · 5 esai.</p><h3>A. Pilihan Ganda</h3><ol>{Array.from({length:10},(_,i)=><li key={i}><b>{f[i%f.length]}</b> — pilih jawaban paling tepat.<div>A. ______ B. ______ C. ______ D. ______</div></li>)}</ol><h3>B. Menjodohkan</h3><ol>{Array.from({length:10},(_,i)=><li key={i}>{f[i%f.length]} ↔ ____________________</li>)}</ol><h3>C. Esai/Praktik</h3><ol>{Array.from({length:5},(_,i)=><li key={i}>{mapel==='RUPA'?'Jelaskan atau praktikkan':'Jelaskan'} konsep “{f[i%f.length]}” berdasarkan pembelajaran.<div>________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}

export function Kelas5MapelMasterScreen(){const{mapelKode='',babNo='',mode='hub'}=useParams();const mapel=mapelKode.toUpperCase();const d=useMemo(()=>sumberData(mapel,babNo),[mapel,babNo]);const buku=BUKU_MASTER_KELAS5.find(x=>x.mapel_kode===mapel);const ekstra=LINGKUP_KKA_RUPA_KELAS5.filter(x=>x.mapel===mapel);const list=ekstra.length?ekstra.map(x=>({id:x.id,nomor_tampil:x.nomor,judul_bab:x.judul,topik:x.topik,sumber:x.sumber})):(buku?BAB_MASTER_KELAS5.filter(x=>x.buku_id===buku.id).map(x=>({id:x.id,nomor_tampil:String(x.nomor_tampil),judul_bab:x.judul_bab,topik:TOPIK_MASTER_KELAS5.filter(t=>t.bab_id===x.id).map(t=>t.judul_topik),sumber:buku.judul})):[]);if(!buku)return <main className="k5-content"><h1>Referensi mapel belum tersedia</h1></main>;if(mode==='hub'||!babNo)return <main className="k5-content"><header className="k5-content__header"><div><small>Kelas V · Referensi Pembelajaran</small><h1>{IKON[mapel]} {LABEL[mapel]}</h1><p>{buku.judul} · {buku.penerbit}</p></div></header><section className="k5-lkpd-grid">{list.map(b=><article key={b.id}><h3>{b.nomor_tampil} · {b.judul_bab}</h3><p>{b.topik.join(' · ')}</p><small>Sumber: {b.sumber}</small><div className="k5-options">{(['game','vlab','kuis','lkpd','bank-soal'] as Mode[]).map(m=><Link key={m} className="k5-primary" to={`/kelas5/${mapel}/${encodeURIComponent(b.nomor_tampil)}/${m}`}>{m}</Link>)}</div></article>)}</section></main>;if(!d.bab)return <main className="k5-content"><h1>Materi tidak ditemukan</h1></main>;return <main className="k5-content"><header className="k5-content__header"><Link to={`/kelas5/${mapel}`}>←</Link><div><small>{LABEL[mapel]} Kelas V</small><h1>{d.bab.nomor_tampil} · {d.bab.judul_bab}</h1><p>{d.sumber}</p></div></header>{mode==='game'?<GameStage mapel={mapel} judul={d.bab.judul_bab} topik={d.topik}/>:mode==='vlab'?<LabStage mapel={mapel} judul={d.bab.judul_bab} topik={d.topik}/>:mode==='kuis'?<Kuis mapel={mapel} topik={d.topik}/>:mode==='lkpd'?<Lkpd mapel={mapel} judul={d.bab.judul_bab} topik={d.topik}/>:<Bank mapel={mapel} judul={d.bab.judul_bab} topik={d.topik}/>}</main>}
