import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './kelas5-bab2-content.css';

type Jenis='kuis'|'lkpd'|'bank-soal';
const FOKUS=['Mengenali keberagaman budaya daerah dan pentingnya saling menghargai.','Menjelaskan contoh kegiatan ekonomi di daerah serta alur produksi, distribusi, dan konsumsi.','Mengidentifikasi potensi daerah yang dapat menjadi kebanggaan dan cara menjaganya.'] as const;
const KUIS=[{q:'Contoh unsur budaya daerah adalah...',o:['bahasa daerah','arus listrik','bayangan','magnet'],a:0},{q:'Sikap yang tepat terhadap perbedaan budaya adalah...',o:['menghargai','mengejek','menghapus','menghindari semua perbedaan'],a:0},{q:'Kegiatan membuat barang disebut...',o:['produksi','distribusi','konsumsi','pelapukan'],a:0},{q:'Kegiatan menyalurkan barang dari produsen ke konsumen disebut...',o:['distribusi','produksi','konsumsi','erosi'],a:0},{q:'Potensi daerah dapat dijaga dengan...',o:['merawat budaya, lingkungan, dan fasilitas','merusak fasilitas','membuang sampah','menghilangkan produk lokal'],a:0}];
const PG=['Contoh keragaman budaya adalah...','Bahasa daerah termasuk unsur...','Cara melestarikan budaya adalah...','Orang yang menghasilkan barang disebut...','Kegiatan menyalurkan barang disebut...','Orang yang menggunakan barang/jasa disebut...','Potensi ekonomi daerah dapat dipengaruhi oleh...','Kerajinan khas dapat menjadi...','Lingkungan yang terawat dapat membantu...','Kebanggaan daerah sebaiknya diwujudkan dengan...'];
const JODOH=[['Bahasa daerah','unsur budaya'],['Tari tradisional','kesenian daerah'],['Produksi','membuat barang/jasa'],['Distribusi','menyalurkan barang/jasa'],['Konsumsi','menggunakan barang/jasa'],['Potensi daerah','keunggulan yang dapat dikembangkan'],['Kerajinan','produk kreatif daerah'],['Pelestarian','upaya menjaga budaya'],['Promosi','mengenalkan potensi daerah'],['Gotong royong','kerja bersama untuk kepentingan bersama']];
const ESAI=['Sebutkan tiga contoh budaya daerah yang kamu ketahui.','Jelaskan mengapa kita perlu menghargai perbedaan budaya.','Jelaskan alur produksi, distribusi, dan konsumsi dengan satu contoh.','Sebutkan dua potensi ekonomi yang mungkin ada di suatu daerah.','Tuliskan dua cara yang dapat dilakukan siswa untuk menjaga kebanggaan daerah.'];
function Kuis(){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=KUIS[Math.min(i,KUIS.length-1)];if(i>=KUIS.length)return <section className="k5-content-card"><h2>Kuis selesai</h2><div className="k5-score">{skor}/{KUIS.length*100}</div><button onClick={()=>{setI(0);setSkor(0)}}>Ulangi</button></section>;return <section className="k5-content-card"><p className="k5-kicker">Soal {i+1}/{KUIS.length}</p><h2>{x.q}</h2><div className="k5-options">{x.o.map((o,n)=><button key={o} onClick={()=>{if(n===x.a)setSkor(skor+100);setI(i+1)}}>{String.fromCharCode(65+n)}. {o}</button>)}</div></section>}
function Lkpd(){return <section className="k5-worksheet"><div className="k5-worksheet__banner">🎭 🏪 LKPD IPAS KELAS V ⭐</div><h2>Bab 7 — Daerahku Kebanggaanku</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid"><article><h3>🎭 Aktivitas 1 · Budaya Daerah</h3><p>Tuliskan tiga contoh budaya daerah yang kamu ketahui.</p><p>1. __________________</p><p>2. __________________</p><p>3. __________________</p></article><article><h3>🏪 Aktivitas 2 · Alur Ekonomi</h3><p>Pilih satu produk lokal dan tuliskan alurnya.</p><p>Produksi: ______________________________</p><p>Distribusi: _____________________________</p><p>Konsumsi: ______________________________</p></article><article><h3>⭐ Aktivitas 3 · Potensi Daerah</h3><p>Tuliskan satu potensi daerah dan cara menjaganya.</p><p>Potensi: _______________________________</p><p>Cara menjaga: __________________________</p></article><article><h3>🤝 Refleksi</h3><p>Mengapa kita perlu menghargai budaya dan pekerjaan masyarakat yang beragam?</p><p>__________________________________________________</p></article></div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank(){return <section className="k5-bank"><h2>Bank Soal IPAS Kelas V · Bab 7</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{PG.map((q,i)=><li key={q}><b>{q}</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><div className="k5-match">{JODOH.map(([a,b],i)=><div key={a}><b>{i+1}. {a}</b><span>↔</span><span>{b}</span></div>)}</div><h3>C. Esai</h3><ol>{ESAI.map(q=><li key={q}>{q}<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5Bab7ContentScreen(){const path=useLocation().pathname;const jenis:Jenis=path.includes('bank-soal')?'bank-soal':path.includes('lkpd')?'lkpd':'kuis';return <main className="k5-content"><header className="k5-content__header"><Link to={RUTE.dasbor}>←</Link><div><small>IPAS Kelas V · Buku Referensi · Bab 7</small><h1>{jenis==='kuis'?'⚡ Kuis Langsung':jenis==='lkpd'?'🎨 LKPD Interaktif':'📚 Bank Soal'}</h1><p>Daerahku Kebanggaanku</p></div></header><aside className="k5-tujuan"><b>Fokus belajar Bab 7</b>{FOKUS.map(x=><span key={x}>• {x}</span>)}</aside>{jenis==='kuis'?<Kuis/>:jenis==='lkpd'?<Lkpd/>:<Bank/>}</main>}
