import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './kelas5-bab2-content.css';

type Jenis='kuis'|'lkpd'|'bank-soal';
const FOKUS=['Mengenali Indonesia sebagai negara kepulauan.','Mengenali kekayaan hayati Indonesia dan hubungan makhluk hidup dengan habitatnya.','Membedakan contoh sumber daya alam serta pentingnya pemanfaatan yang bijak.'] as const;
const KUIS=[{q:'Indonesia disebut negara kepulauan karena...',o:['terdiri atas banyak pulau','hanya memiliki satu pulau','tidak memiliki laut','seluruh wilayahnya pegunungan'],a:0},{q:'Keanekaragaman hayati berarti...',o:['beragam jenis makhluk hidup','satu jenis makhluk hidup saja','semua benda mati','hanya tumbuhan'],a:0},{q:'Habitat adalah...',o:['tempat hidup organisme','alat listrik','sumber bunyi','lapisan cahaya'],a:0},{q:'Contoh sumber daya yang dapat diperbarui adalah...',o:['angin','minyak bumi','batu bara','gas alam'],a:0},{q:'Pemanfaatan hutan yang lebih bijak adalah...',o:['tebang pilih dan tanam kembali','menebang seluruh pohon','membakar lahan','membuang limbah ke hutan'],a:0}];
const PG=['Indonesia memiliki banyak pulau sehingga disebut...','Contoh kekayaan hayati adalah...','Habitat diperlukan makhluk hidup untuk...','Keragaman jenis makhluk hidup disebut...','Sumber daya alam dimanfaatkan manusia untuk...','Contoh sumber daya dapat diperbarui adalah...','Contoh sumber daya yang pulih sangat lambat adalah...','Pengelolaan hutan berkelanjutan dapat dilakukan dengan...','Pemanfaatan air yang bijak adalah...','Menjaga habitat penting karena...'];
const JODOH=[['Kepulauan','wilayah yang terdiri atas banyak pulau'],['Laut','wilayah perairan luas'],['Keanekaragaman hayati','keragaman makhluk hidup'],['Habitat','tempat hidup organisme'],['Hutan','salah satu ekosistem daratan'],['Angin','sumber daya dapat diperbarui'],['Matahari','sumber energi terbarukan'],['Minyak bumi','sumber daya yang pulih sangat lambat'],['Konservasi','upaya menjaga sumber daya/keanekaragaman'],['Pemanfaatan bijak','menggunakan sumber daya dengan mempertimbangkan kelestarian']];
const ESAI=['Jelaskan mengapa Indonesia disebut negara kepulauan.','Berikan tiga contoh kekayaan hayati Indonesia yang kamu ketahui.','Jelaskan hubungan makhluk hidup dengan habitatnya.','Bandingkan sumber daya yang dapat diperbarui dan yang pulih sangat lambat.','Tuliskan dua cara sederhana menggunakan sumber daya alam secara bijak.'];
function Kuis(){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=KUIS[Math.min(i,KUIS.length-1)];if(i>=KUIS.length)return <section className="k5-content-card"><h2>Kuis selesai</h2><div className="k5-score">{skor}/{KUIS.length*100}</div><button onClick={()=>{setI(0);setSkor(0)}}>Ulangi</button></section>;return <section className="k5-content-card"><p className="k5-kicker">Soal {i+1}/{KUIS.length}</p><h2>{x.q}</h2><div className="k5-options">{x.o.map((o,n)=><button key={o} onClick={()=>{if(n===x.a)setSkor(skor+100);setI(i+1)}}>{String.fromCharCode(65+n)}. {o}</button>)}</div></section>}
function Lkpd(){return <section className="k5-worksheet"><div className="k5-worksheet__banner">🗺️ 🦜 LKPD IPAS KELAS V ♻️</div><h2>Bab 6 — Indonesiaku Kaya Raya</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid"><article><h3>🗺️ Aktivitas 1 · Indonesiaku</h3><p>Tuliskan lima pulau besar yang kamu ketahui.</p><p>1. ______ 2. ______ 3. ______ 4. ______ 5. ______</p></article><article><h3>🦜 Aktivitas 2 · Kekayaan Hayati</h3><p>Tuliskan tiga contoh hewan/tumbuhan Indonesia dan habitatnya.</p><p>1. __________ → __________</p><p>2. __________ → __________</p><p>3. __________ → __________</p></article><article><h3>⛏️ Aktivitas 3 · Sumber Daya</h3><p>Kelompokkan contoh sumber daya yang dapat diperbarui dan yang pulih sangat lambat.</p><p>Dapat diperbarui: __________________________</p><p>Pulih sangat lambat: _______________________</p></article><article><h3>♻️ Refleksi</h3><p>Apa yang dapat dilakukan siswa untuk membantu menggunakan sumber daya secara bijak?</p><p>__________________________________________________</p></article></div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank(){return <section className="k5-bank"><h2>Bank Soal IPAS Kelas V · Bab 6</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{PG.map((q,i)=><li key={q}><b>{q}</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><div className="k5-match">{JODOH.map(([a,b],i)=><div key={a}><b>{i+1}. {a}</b><span>↔</span><span>{b}</span></div>)}</div><h3>C. Esai</h3><ol>{ESAI.map(q=><li key={q}>{q}<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5Bab6ContentScreen(){const path=useLocation().pathname;const jenis:Jenis=path.includes('bank-soal')?'bank-soal':path.includes('lkpd')?'lkpd':'kuis';return <main className="k5-content"><header className="k5-content__header"><Link to={RUTE.dasbor}>←</Link><div><small>IPAS Kelas V · Buku Referensi · Bab 6</small><h1>{jenis==='kuis'?'⚡ Kuis Langsung':jenis==='lkpd'?'🎨 LKPD Interaktif':'📚 Bank Soal'}</h1><p>Indonesiaku Kaya Raya</p></div></header><aside className="k5-tujuan"><b>Fokus belajar Bab 6</b>{FOKUS.map(x=><span key={x}>• {x}</span>)}</aside>{jenis==='kuis'?<Kuis/>:jenis==='lkpd'?<Lkpd/>:<Bank/>}</main>}
