import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { RUTE } from '../../routes/paths';
import './kelas5-bab2-content.css';

type Jenis='kuis'|'lkpd'|'bank-soal';
const FOKUS=['Menjelaskan hubungan pernapasan dengan aktivitas sehari-hari.','Menjelaskan peran makanan dan minuman bagi tubuh secara umum.','Mengenali bahwa manusia tumbuh dan berkembang melalui tahapan kehidupan.'] as const;
const KUIS=[{q:'Saat aktivitas meningkat, tubuh pada umumnya membutuhkan...',o:['lebih banyak pertukaran gas','lebih sedikit udara selalu','tidak membutuhkan oksigen','bunyi lebih keras'],a:0},{q:'Udara masuk ke tubuh melalui...',o:['hidung atau mulut menuju saluran napas','kulit menuju tulang','mata menuju lambung','telinga menuju paru-paru'],a:0},{q:'Karbohidrat secara umum berperan sebagai...',o:['salah satu sumber energi','pembentuk cahaya','penghasil magnet','pengubah tanah'],a:0},{q:'Organ pencernaan yang menerima makanan setelah mulut adalah...',o:['lambung melalui saluran pencernaan','paru-paru','mata','telinga'],a:0},{q:'Pertumbuhan manusia berlangsung...',o:['bertahap sepanjang kehidupan','langsung dari bayi menjadi dewasa','hanya saat tidur','tanpa perubahan kemampuan'],a:0}];
const PG=['Fungsi utama sistem pernapasan adalah...','Saat berlari, frekuensi napas biasanya...','Udara pertama kali masuk melalui...','Paru-paru berperan dalam...','Makanan dibutuhkan tubuh untuk...','Contoh zat gizi sumber energi adalah...','Protein membantu tubuh dalam...','Air penting bagi tubuh karena...','Pertumbuhan manusia ditandai oleh...','Kebiasaan sehat yang mendukung pertumbuhan adalah...'];
const JODOH=[['Hidung','jalan masuk udara'],['Paru-paru','tempat pertukaran gas'],['Frekuensi napas','jumlah napas per waktu'],['Karbohidrat','sumber energi'],['Protein','membantu pembentukan jaringan'],['Vitamin/mineral','membantu berbagai proses tubuh'],['Air','mendukung berbagai fungsi tubuh'],['Mulut','awal proses pencernaan'],['Usus halus','tempat utama penyerapan zat gizi'],['Pertumbuhan','perubahan bertahap sepanjang kehidupan']];
const ESAI=['Jelaskan mengapa frekuensi napas dapat meningkat saat beraktivitas.','Tuliskan jalur udara secara sederhana dari luar tubuh menuju paru-paru.','Jelaskan mengapa tubuh memerlukan makanan dan minuman.','Tuliskan urutan sederhana perjalanan makanan melalui organ pencernaan utama.','Jelaskan dua kebiasaan sehat yang dapat mendukung pertumbuhan dan kegiatan belajar.'];
function Kuis(){const[i,setI]=useState(0);const[skor,setSkor]=useState(0);const x=KUIS[Math.min(i,KUIS.length-1)];if(i>=KUIS.length)return <section className="k5-content-card"><h2>Kuis selesai</h2><div className="k5-score">{skor}/{KUIS.length*100}</div><button onClick={()=>{setI(0);setSkor(0)}}>Ulangi</button></section>;return <section className="k5-content-card"><p className="k5-kicker">Soal {i+1}/{KUIS.length}</p><h2>{x.q}</h2><div className="k5-options">{x.o.map((o,n)=><button key={o} onClick={()=>{if(n===x.a)setSkor(skor+100);setI(i+1)}}>{String.fromCharCode(65+n)}. {o}</button>)}</div></section>}
function Lkpd(){return <section className="k5-worksheet"><div className="k5-worksheet__banner">🫁 🥗 LKPD IPAS KELAS V 🌱</div><h2>Bab 5 — Bagaimana Kita Hidup dan Bertumbuh</h2><div className="k5-identitas"><span>Nama: ____________________</span><span>Kelompok: __________</span><span>Tanggal: __________</span></div><div className="k5-lkpd-grid"><article><h3>🫁 Aktivitas 1 · Napas dan Aktivitas</h3><p>Gunakan VLAB Breathing Rate. Bandingkan tiga tingkat aktivitas.</p><table><tbody><tr><th>Aktivitas</th><th>Frekuensi model</th></tr><tr><td>Duduk</td><td>__________</td></tr><tr><td>Berjalan</td><td>__________</td></tr><tr><td>Berlari</td><td>__________</td></tr></tbody></table></article><article><h3>🍽️ Aktivitas 2 · Perjalanan Makanan</h3><p>Susun urutan: mulut → __________ → __________ → __________.</p><p>Apa yang terjadi pada tiap tahap? __________________________</p></article><article><h3>🥗 Aktivitas 3 · Peran Zat Gizi</h3><p>Tuliskan satu contoh makanan untuk tiap kelompok zat gizi yang dibahas.</p><p>Karbohidrat: __________</p><p>Protein: __________</p><p>Vitamin/mineral: __________</p></article><article><h3>🌱 Refleksi</h3><p>Tuliskan dua kebiasaan sehat yang membantumu belajar dan beraktivitas.</p><p>1. ______________________________________________</p><p>2. ______________________________________________</p></article></div><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
function Bank(){return <section className="k5-bank"><h2>Bank Soal IPAS Kelas V · Bab 5</h2><p>10 pilihan ganda · 10 menjodohkan · 5 esai</p><h3>A. Pilihan Ganda</h3><ol>{PG.map((q,i)=><li key={q}><b>{q}</b><div className="k5-lines">A. __________ &nbsp; B. __________ &nbsp; C. __________ &nbsp; D. __________</div><small>Tingkat: {i<4?'Mudah':i<8?'Sedang':'Sulit'}</small></li>)}</ol><h3>B. Menjodohkan</h3><div className="k5-match">{JODOH.map(([a,b],i)=><div key={a}><b>{i+1}. {a}</b><span>↔</span><span>{b}</span></div>)}</div><h3>C. Esai</h3><ol>{ESAI.map(q=><li key={q}>{q}<div className="k5-answer-lines">____________________________________________________<br/>____________________________________________________</div></li>)}</ol><button className="k5-print" onClick={()=>window.print()}>🖨️ Cetak / Simpan PDF</button></section>}
export function Kelas5Bab5ContentScreen(){const path=useLocation().pathname;const jenis:Jenis=path.includes('bank-soal')?'bank-soal':path.includes('lkpd')?'lkpd':'kuis';return <main className="k5-content"><header className="k5-content__header"><Link to={RUTE.dasbor}>←</Link><div><small>IPAS Kelas V · Buku Referensi · Bab 5</small><h1>{jenis==='kuis'?'⚡ Kuis Langsung':jenis==='lkpd'?'🎨 LKPD Interaktif':'📚 Bank Soal'}</h1><p>Bagaimana Kita Hidup dan Bertumbuh</p></div></header><aside className="k5-tujuan"><b>Fokus belajar Bab 5</b>{FOKUS.map(x=><span key={x}>• {x}</span>)}</aside>{jenis==='kuis'?<Kuis/>:jenis==='lkpd'?<Lkpd/>:<Bank/>}</main>}
