import { useMemo, useState } from 'react';

type Props={mapel:'KKA'|'RUPA'; topik:string[]; mode:'game'|'vlab'};

const KKA_GAME=['Robot Instruksi','Pecahkan Masalah','Penjaga Data','AI atau Bukan?','Klasifikasi Pintar'] as const;
const RUPA_GAME=['Mix & Match Warna','Susun Komposisi','Ragam Hias Hunt','Studio Ekspresi','Kurator Cilik'] as const;

function RobotInstruksi(){const target=['Maju','Maju','Kanan','Maju'];const[isi,setIsi]=useState<string[]>([]);const selesai=isi.length===target.length&&isi.every((x,i)=>x===target[i]);return <div className="k5-content-card"><h2>🤖 Robot Instruksi</h2><p>Susun perintah agar robot bergerak: maju, maju, kanan, maju.</p><div className="k5-options">{['Maju','Kanan','Kiri'].map(x=><button key={x} onClick={()=>setIsi(v=>v.length<4?[...v,x]:v)}>{x}</button>)}<button onClick={()=>setIsi([])}>Reset</button></div><div className="k5-score">{isi.join(' → ')||'Belum ada instruksi'}</div><p>{selesai?'🏆 Urutan logis berhasil!':isi.length===4?'Urutan belum tepat. Coba lagi.':'Lengkapi empat langkah.'}</p></div>}
function ProblemSolver(){const tahap=['Pahami masalah','Pecah menjadi bagian','Susun langkah','Uji solusi'];const[urutan,setUrutan]=useState<string[]>([]);return <div className="k5-content-card"><h2>🧩 Pecahkan Masalah</h2><p>Susun proses pemecahan masalah secara sistematis.</p><div className="k5-options">{[...tahap].reverse().map(x=><button key={x} disabled={urutan.includes(x)} onClick={()=>setUrutan(v=>[...v,x])}>{x}</button>)}</div><div className="k5-score">{urutan.join(' → ')||'Pilih langkah'}</div><p>{urutan.length===4&&urutan.every((x,i)=>x===tahap[i])?'🏆 Sistematis dan benar.':urutan.length===4?'Belum runtut. Reset dan coba lagi.':''}</p><button onClick={()=>setUrutan([])}>Reset</button></div>}
function DataGuard(){const kasus=[['Nama panggilan untuk avatar kelas','aman'],['Kata sandi akun','rahasia'],['Alamat rumah lengkap di ruang publik','rahasia'],['Hobi favorit','aman']] as const;const[i,setI]=useState(0),[skor,setSkor]=useState(0);const x=kasus[i%kasus.length];return <div className="k5-content-card"><h2>🔐 Penjaga Data</h2><p>{x[0]}</p><div className="k5-options"><button onClick={()=>{if(x[1]==='aman')setSkor(s=>s+1);setI(n=>n+1)}}>Boleh dibagikan pada konteks aman</button><button onClick={()=>{if(x[1]==='rahasia')setSkor(s=>s+1);setI(n=>n+1)}}>Jaga sebagai informasi pribadi</button></div><div className="k5-score">Skor {skor} · Putaran {i+1}</div><small>Jangan masukkan data pribadi sungguhan ke latihan ini.</small></div>}
function AiOrNot(){const data=[['Kipas angin biasa','non'],['Robot penyapu otomatis yang mengenali rute','ai'],['Setrika biasa','non'],['Asisten suara yang mengenali ucapan','ai']] as const;const[i,setI]=useState(0),[skor,setSkor]=useState(0);const x=data[i%data.length];return <div className="k5-content-card"><h2>🧠 AI atau Bukan?</h2><p>{x[0]}</p><div className="k5-options"><button onClick={()=>{if(x[1]==='ai')setSkor(s=>s+1);setI(n=>n+1)}}>Mesin cerdas/KA</button><button onClick={()=>{if(x[1]==='non')setSkor(s=>s+1);setI(n=>n+1)}}>Mesin non-cerdas</button></div><div className="k5-score">Skor {skor}</div></div>}
function Classify(){const objek=[['🍎 Apel','buah'],['🥕 Wortel','sayur'],['🍌 Pisang','buah'],['🥦 Brokoli','sayur']] as const;const[i,setI]=useState(0),[skor,setSkor]=useState(0);const x=objek[i%objek.length];return <div className="k5-content-card"><h2>🎯 Klasifikasi Pintar</h2><p>Klasifikasikan berdasarkan ciri sederhana: {x[0]}</p><div className="k5-options"><button onClick={()=>{if(x[1]==='buah')setSkor(s=>s+1);setI(n=>n+1)}}>Buah</button><button onClick={()=>{if(x[1]==='sayur')setSkor(s=>s+1);setI(n=>n+1)}}>Sayur</button></div><div className="k5-score">Skor {skor}</div></div>}

function KkaGame(){const[m,setM]=useState(0);const isi=[<RobotInstruksi/>,<ProblemSolver/>,<DataGuard/>,<AiOrNot/>,<Classify/>];return <><nav className="k5-options">{KKA_GAME.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{i+1}. {x}</button>)}</nav>{isi[m]}</>}
function KkaLab(){const[m,setM]=useState(0),[input,setInput]=useState(50),[aturan,setAturan]=useState(50);const labs=['Simulator Urutan','Lab Sistem Komputer','Lab Privasi Digital','Lab Sensor Manusia vs Komputer','Lab Data & Prediksi'];const hasil=useMemo(()=>Math.round((input*0.6)+(aturan*0.4)),[input,aturan]);return <><nav className="k5-options">{labs.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{i+1}. {x}</button>)}</nav><section className="k5-content-card"><h2>💻 {labs[m]}</h2>{m===0&&<p>Ubah jumlah langkah dan ketelitian aturan untuk melihat keberhasilan instruksi.</p>}{m===1&&<p>Modelkan hubungan input → proses → output pada sistem komputer sederhana.</p>}{m===2&&<p>Bandingkan banyaknya informasi yang dibagikan dengan tingkat perlindungannya. Gunakan data contoh saja.</p>}{m===3&&<p>Bandingkan kemampuan sensor sederhana dengan penginderaan manusia dalam skenario model.</p>}{m===4&&<p>Amati bagaimana kualitas/jumlah data input dapat mengubah hasil prediksi model.</p>}<label>Input/Data <b>{input}</b><input type="range" min="0" max="100" value={input} onChange={e=>setInput(+e.target.value)}/></label><label>Aturan/Kualitas <b>{aturan}</b><input type="range" min="0" max="100" value={aturan} onChange={e=>setAturan(+e.target.value)}/></label><div className="k5-score">Hasil model: {hasil}%</div><p>Kesimpulan: perubahan input atau aturan dapat mengubah hasil sistem.</p></section></>}

function ColorMix(){const[r,setR]=useState(220),[g,setG]=useState(120),[b,setB]=useState(80);return <div className="k5-content-card"><h2>🎨 Mix & Match Warna</h2><div style={{height:170,borderRadius:20,background:`rgb(${r},${g},${b})`}}/><label>Merah<input type="range" min="0" max="255" value={r} onChange={e=>setR(+e.target.value)}/></label><label>Hijau<input type="range" min="0" max="255" value={g} onChange={e=>setG(+e.target.value)}/></label><label>Biru<input type="range" min="0" max="255" value={b} onChange={e=>setB(+e.target.value)}/></label><p>Amati bagaimana perubahan warna memengaruhi suasana visual.</p></div>}
function Balance(){const[pos,setPos]=useState(50),[besar,setBesar]=useState(50);return <div className="k5-content-card"><h2>🧩 Susun Komposisi</h2><div style={{height:180,position:'relative',border:'2px solid currentColor',borderRadius:18,overflow:'hidden'}}><span style={{position:'absolute',left:`${Math.max(5,pos-5)}%`,top:'35%',fontSize:`${24+besar/2}px`}}>●</span><span style={{position:'absolute',right:`${Math.max(5,pos-5)}%`,top:'35%',fontSize:`${24+(100-besar)/2}px`}}>▲</span></div><label>Posisi keseimbangan<input type="range" min="10" max="90" value={pos} onChange={e=>setPos(+e.target.value)}/></label><label>Perbandingan ukuran<input type="range" min="10" max="90" value={besar} onChange={e=>setBesar(+e.target.value)}/></label><p>Carilah komposisi yang terasa seimbang walau bentuk berbeda.</p></div>}
function Motif(){const[jenis,setJenis]=useState<'flora'|'fauna'|'geo'>('flora');const ikon={flora:'🌺',fauna:'🦋',geo:'◆'}[jenis];return <div className="k5-content-card"><h2>🌺 Ragam Hias Hunt</h2><div className="k5-options"><button onClick={()=>setJenis('flora')}>Flora</button><button onClick={()=>setJenis('fauna')}>Fauna</button><button onClick={()=>setJenis('geo')}>Geometris</button></div><div style={{fontSize:46,letterSpacing:20,textAlign:'center',padding:30}}>{ikon}{ikon}{ikon}{ikon}{ikon}</div><p>Perhatikan pengulangan, ritme, dan jenis motif.</p></div>}
function Expression(){const[energi,setEnergi]=useState(60);return <div className="k5-content-card"><h2>✏️ Studio Ekspresi</h2><label>Energi garis<input type="range" min="0" max="100" value={energi} onChange={e=>setEnergi(+e.target.value)}/></label><div style={{padding:30,fontSize:40,transform:`skew(${(energi-50)/5}deg)`,letterSpacing:`${energi/10}px`}}>〰〰〰 ✦ 〰〰〰</div><p>Bandingkan garis tenang dan garis dinamis, lalu ceritakan perasaan yang muncul.</p></div>}
function Curator(){const karya=['Komposisi simetris','Komposisi memancar','Ragam hias flora','Gambar ekspresif'];const[i,setI]=useState(0);return <div className="k5-content-card"><h2>🏆 Kurator Cilik</h2><p>Karya: <b>{karya[i%karya.length]}</b></p><textarea rows={4} placeholder="Tuliskan unsur rupa, prinsip, dan alasan apresiasimu…"/><button onClick={()=>setI(n=>n+1)}>Karya berikut →</button></div>}
function RupaGame(){const[m,setM]=useState(0);const isi=[<ColorMix/>,<Balance/>,<Motif/>,<Expression/>,<Curator/>];return <><nav className="k5-options">{RUPA_GAME.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{i+1}. {x}</button>)}</nav>{isi[m]}</>}
function RupaLab(){const[m,setM]=useState(0),[a,setA]=useState(50),[b,setB]=useState(50);const labs=['Lab Keseimbangan','Lab Proporsi','Lab Kontras Warna','Lab Ritme Motif','Lab Gelap-Terang'];return <><nav className="k5-options">{labs.map((x,i)=><button key={x} aria-pressed={m===i} onClick={()=>setM(i)}>{i+1}. {x}</button>)}</nav><section className="k5-content-card"><h2>🎨 {labs[m]}</h2><div style={{height:180,borderRadius:18,display:'grid',placeItems:'center',fontSize:50,background:`linear-gradient(${45+a}deg,hsl(${a*3.6} 70% ${30+b/2}%),hsl(${b*3.6} 70% ${80-a/3}%))`}}>◆ ● ✦ ▲</div><label>Variabel visual A<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)}/></label><label>Variabel visual B<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)}/></label><p>Ubah kedua variabel dan catat bagaimana komposisi, proporsi, kontras, ritme, atau gelap-terang terasa berubah.</p></section></>}

export function Kelas5KkaRupaInteraktif({mapel,mode}:Props){if(mapel==='KKA')return mode==='game'?<KkaGame/>:<KkaLab/>;return mode==='game'?<RupaGame/>:<RupaLab/>;}
